### ISSUE TITLE
support for ASCIIHexDecode filter

### ISSUE THREAD

**Issue by Lidia321** [galkahana/PDF-Writer#106]
Hello Gal,

Do you have any plans to implement ASCIIHexDecode for stream in nearest future ?

As usual, many thanks for this wonderful library.
Lidia.

**Comment by galkahana** [comment]
Aint on my plate no. Wanna contrib?

**Comment by Lidia321** [comment]
OK.

**Comment by Lidia321** [comment]
[PDFWriter.zip](https://github.com/galkahana/PDF-Writer/files/1329255/PDFWriter.zip)
Attached are changes/additions for AsciiHexDecode filter support. 
It's really minor things, so I hope there are no bugs here.
Sorry, I haven't made it properly - with git fork and so on - I do not work with projects you've created.

**Comment by galkahana** [comment]
wonderful! i'll incorporate and let you know.

**Comment by galkahana** [comment]
@Lidia321, introduced your code to https://github.com/galkahana/PDF-Writer/commit/31dc6a7abbcdfbff18b028d9c69b2dc1290b73b9
Thank you!
