### ISSUE TITLE
possible memory leak or what am i doing wrong

### ISSUE THREAD

**Issue by Lidia321** [galkahana/PDF-Writer#109]
Hello Gal,

The code below got memory leak after each assignment.
{
        RefCountPtr<PDFObject> anObject(objectParser->ParseNewObject());
	while (anObject.GetPtr()) 
	{
		anObject = objectParser->ParseNewObject()
	}
}
But this one - does not.
{
        RefCountPtr<PDFObject> anObject(objectParser->ParseNewObject());
	while (anObject.GetPtr()) 
	{
		RefCountPtr<PDFObject> t(objectParser->ParseNewObject());
		anObject = t;
	}
}

As far as understand, it should be same.
Could you please explain what is wrong with first piece ?

Thanks and cheers.
Lidia.

**Comment by galkahana** [comment]
see here:
https://github.com/galkahana/PDF-Writer/blob/master/PDFWriter/RefCountPtr.h#L51-L53

both ParseNewObject and the assignment operator do addRef:

- ParseNewObject does this naturally, assuming that its value is introduced into a ref pointer as init value. same as any "new" would do for an object with ref count
- Assignment to ref count pointer also bumps up the ref count, as there's a new reference created. or at least, that's the assumption.

What you do in the 2nd part is a good way to avoid the problem, by assigning directly to a function pointer.

In general, it's better that objects with ref count are assigned to smart pointer first, and then you do other assignments - that would generate more expected results.

**Comment by Lidia321** [comment]
great,thanks
