### ISSUE TITLE
LZW encoded streams support

### ISSUE THREAD

**Issue by Lidia321** [galkahana/PDF-Writer#112]
Hi Gal,

Just for case : are you going to add support for LZW encoded stream in the nearest future ?

Thanks.
Lidia.

**Comment by Lidia321** [comment]
Anyway, attached is implementation.
It would be nice to have it inside when and if library is updated.
[PDFWriter.zip](https://github.com/galkahana/PDF-Writer/files/1591486/PDFWriter.zip)



Thanks.
Lidia.

**Comment by galkahana** [comment]
@Lidia321 . So many years afterwards, while working on the first PDF project in years, I suddenly needed to parse a PDF file that has LZW code in it. found your note here from way back...and would like to thank you very much for this!

**Comment by galkahana** [comment]
part of master now with e3e468f865ba193a91c2d945fa0f9e12be8f3df2.
Thank you!

**Comment by Lidia321** [comment]
Yep...
Once upon a time :).
Cool !
