### ISSUE TITLE
Writing accent

### ISSUE THREAD

**Issue by tiflap** [galkahana/PDF-Writer#115]
Hello,
I am wondering if there is a way to write text with french accent (like é, è or ï) in the pdf?
Cause when I put a text with accent, using the Tj function, nothing is written.

Thank a lot.

**Comment by galkahana** [comment]
code in utf8 and make sure the font supports the char.
for easier text placement, consider using WriteText method instead (https://github.com/galkahana/PDF-Writer/wiki/Text-support#simple-text-usage) [not different functionality, but less code to write].
