### ISSUE TITLE
writer.ModifyPDF with erroneous path segfaults

### ISSUE THREAD

**Issue by gnat42** [galkahana/PDF-Writer#116]
When doing the following

```
writer.ModifyPDF(inputPath,ePDFVersion14,outputPath)
...
writer.EndPDF();
```
Where output path doesn't exist yet (specifically in our case the directory). The program segfaults. We've added checks to our program but it seems like this really should be in the underlying library or at least it shouldn't segfault.

Thoughts?

**Comment by gnat42** [comment]
So it seems that I should be checking the return status of ModifyPDF and StartPDF for success. 

I kinda wonder about throwing an exception there. It seems like it would be better designed if you couldn't get an object into an invalid state that would continue to allow you to interact with it and then later segfault. Thoughts?

**Comment by galkahana** [comment]
i always preferred statuses to exceptions. that's how hummus is built.

**Comment by gnat42** [comment]
Ok, perhaps I'll submit a PR to the wiki page to show samples with return status checking since it didn't seem obvious to me for whatever reason that I should have been checking the status. Oddly I even looked at the Playground but since it was tests it never dawned on me that checking the return status wasn't there simply for the tests.
