### ISSUE TITLE
Modifying PDF causes corruption / readers think document is encrypted

### ISSUE THREAD

**Issue by gnat42** [galkahana/PDF-Writer#120]
Hello,

  I've got an issue where I'm trying to both add text to pages, and optionally output only a subset of the original documents pages. With some source documents the resulting PDF is detected as encrypted. I've built a simple reproducer. More than likely there is a better way to do this but I wasn't sure how to. This seemed to work 95% of the time. Thoughts? Better ways to implement this?

```

#include <PDFWriter/PDFWriter.h>
#include <PDFWriter/PDFModifiedPage.h>
#include <PDFWriter/PDFPage.h>
#include <PDFWriter/PDFObject.h>
#include <PDFWriter/AbstractContentContext.h>
#include <PDFWriter/EPDFVersion.h>
#include <PDFWriter/PDFUsedFont.h>

using namespace std;

int main() {
    PDFWriter writer;
    writer.ModifyPDF("./File.pdf", ePDFVersionMax, "./Output.pdf");

    PDFModifiedPage thePage(&writer, 0, true);
    AbstractContentContext* contentContext = thePage.StartContentContext();
    PDFUsedFont * _font;

    _font = writer.GetFontForFile("/usr/share/fonts/php-pdf-fonts/arial.ttf", 0);
    AbstractContentContext::TextOptions options(_font, 12, AbstractContentContext::eRGB, 0);
    contentContext->WriteText(100,600, "TEXT IS HERE", options);

    thePage.EndContentContext();
    thePage.WritePage();
    writer.EndPDF();

    PDFPageRange pageRange;
    pageRange.mType = PDFPageRange::eRangeTypeSpecific;
    pageRange.mSpecificRanges.push_back(ULongAndULong(0,3));
    pageRange.mSpecificRanges.push_back(ULongAndULong(10,10));

    writer.StartPDF("./Output-range.pdf", ePDFVersionMax);
    writer.AppendPDFPagesFromPDF("./Output.pdf", pageRange);
    writer.EndPDF();

    return 0;
}
```

So here's the issue. If I run this I get two output PDFs. "Output.pdf" and "Output-range.pdf". The ranged one can't be opened as it thinks it is encrypted. If after the first run I comment out all the parts about writing text, the resulting Output-range.pdf is able to be opened. So it is opening the previously edited PDF and saving only the pages I want. But if I do both operations it gets it wrong.

**Comment by gnat42** [comment]
Additional data, when inspecting the source PDF where this occurs using pdfinfo from poppler-utils I get the following output:

```
Title:          JetForm:AUDIT11.IFD
Creator:        AdobePS5.dll Version 5.1.1
Producer:       Acrobat Distiller 4.05 for Windows
CreationDate:   Thu Feb  8 01:05:29 2001 MST
ModDate:        Wed Mar 12 10:21:41 2014 MDT
Tagged:         no
UserProperties: no
Suspects:       no
Form:           AcroForm
JavaScript:     no
Pages:          49
Encrypted:      yes (print:yes copy:no change:no addNotes:no algorithm:AES)
Page size:      612 x 1008 pts
Page rot:       0
File size:      339819 bytes
Optimized:      no
PDF version:    1.6
```

So it thinks its already encrypted, but its possible to open without entering a password so is what I want to do possible with a document like this?

**Comment by gnat42** [comment]
Finally one last bit. If I use two instances of the PDFWriter then I have no issues.

**Comment by gnat42** [comment]
calling writer.Reset(); does not allow it to work

**Comment by galkahana** [comment]
Well, then you know what to do :).
Not sure i ever planned/tested on using the same pdfWriter for multiple tasks.
if you feel like providing a sample PDF that causes the issue i may look into it some time.
