### ISSUE TITLE
ft2build.h file-not-found error in client app

### ISSUE THREAD

**Issue by samkots** [galkahana/PDF-Writer#130]
Hi Gal,

I am calling the function `PDFUsedFont::CalculateTextDimensions()` in my client app and for the type `PDFUsedFont::TextMeasures`, I need to include the header `<PDFUsedFont.h>`.

But this file includes a freetype's header: `<ft2build.h>` and I get a file-not-found error while compiling the client app.
As a work around I have added freetype's path in the include paths.
Is this expected? Or Is there any way out of this?
Shouldn't the freetype dependency be hidden from the client application?

Also, is there any function that gives you font-height(not text height) for the given font & size?

**Comment by galkahana** [comment]
Im totally cool with you including the ftbuild.h header, so that the code will work for you. my intent is that the code will work.

as for your second question - no, try probing into CalculateTextDimensions or into Freetype to get an answer for this.

**Comment by samkots** [comment]
Great Thanks! :)
