### ISSUE TITLE
create new page by referring to another page objectidtype

### ISSUE THREAD

**Issue by naviialto** [galkahana/PDF-Writer#135]
Hi.
I am now using PDFHummus very well.
One question I have is that I make( writer->StartPDF() ) 1-10 pages and refer to that page and repeat.

I found the WritePageAndReturnPageID and WritePageReleaseAndReturnPageID.

list< ObjectIDType > idlist;
idlist.push( writer-> WritePageAndReturnPageID( page ) );

So I created the code, but it does not work.
ver1
page->AddContentStreamReference( idlist[ pageindex ] );

ver2
context->q();
context->cm(width, 0, 0, height, x, y);
context->Do( page->GetResourcesDictionary().AddXObjectMapping( idlist[ pageindex ] ) );
context->Q();

How do I create a new page by referring to another page objectidtype?

**Comment by galkahana** [comment]
not sure i understand your concept of "page".
a page is a pdf page that appears as a page. you seem to be trying to embed a page in another page. that's not possible.

so let's get a bit of a story here as to what you're trying to do.

Gal.
