### ISSUE TITLE
Combine PDFs while resizing pages

### ISSUE THREAD

**Issue by gnat42** [galkahana/PDF-Writer#141]
Hello,

  I've got a use case where I need to combine multiple PDFs into one while resizing all to be the same page size. Most sample code seems to do one or the other and I'm wondering if what I'd like to do is even possible. 

  So given an array of documents paths, I've been able to combine them using the following code:

```
std::string destinationFile = params[1];
	PDFWriter pdfWriter;
	PDFPageRange pageRange;
	PDFParser parser;
	InputFile pdfFile;
	EStatusCode status = PDFHummus::eSuccess;

	Php::out << "Creating " << destinationFile << std::endl;
	pdfWriter.StartPDF("/tmp/file.pdf",ePDFVersion17);
	
	for (auto &iter : params[0]) {
		if (file_exists(iter.second.stringValue())) {
			pdfWriter.AppendPDFPagesFromPDF(iter.second.stringValue(), pageRange);
			Php::out << "\tWith: " << iter.second.stringValue() << std::endl;
		} else {
			Php::out << "\t " << iter.second.stringValue() << " doesn't exist!" << std::endl;
			return false;
		}
	}

	pdfWriter.EndPDF();
```

In #29 there is a link to some code about the ModifyingExistingFileContent test. However I'm having trouble understanding everything it is doing. When I add it to my particular use case (I modify the PDF I just combined from multiple sources). I can get different page sizes, however its basically just cropping the page, not resizing the content at all.

So a few questions:

 * Is what I want to do possible? 
 * Do I need to open use a PDFWriter instance more than once? Or can I get all source pages and combine it manually while resizing the pages?

Below is the code after the code above that re-opens the modified file and re-writes the mediaBox size. Like I said it resizes the page, but not the content within it...

```
pdfWriter.ModifyPDF(params[1], ePDFVersion17, destinationFile);
	status = pdfFile.OpenFile("/tmp/file.pdf");

	status = parser.StartPDFParsing(pdfFile.GetInputStream());
	if (status != PDFHummus::eSuccess) {
		Php::out << "unable to parse input file" << std::endl;
	} else {
		Php::out << "Pages: " << parser.GetPagesCount() << std::endl;
	}

	PDFDocumentCopyingContext* copyingContext = NULL;

	for (long unsigned int x = 0; x < parser.GetPagesCount(); x++) {
		// Change 3rd page bbox to landscape by modifying the page object
		copyingContext = pdfWriter.CreatePDFCopyingContextForModifiedFile();
		if (!copyingContext) {
			Php::out << "failed to create copying context for modified file" << std::endl;
			status = eFailure;
			return nullptr;
		}
		// create a new object for the page, copy all but media box, which will be changed
		ObjectIDType pageId                     = copyingContext->GetSourceDocumentParser()->GetPageObjectID(x);
		PDFObjectCastPtr<PDFDictionary> pageObj = copyingContext->GetSourceDocumentParser()->ParsePage(x);

		MapIterator<PDFNameToPDFObjectMap> pageObjIt = pageObj->GetIterator();

		pdfWriter.GetObjectsContext().StartModifiedIndirectObject(pageId);
		DictionaryContext* modifiedPageObject = pdfWriter.GetObjectsContext().StartDictionary();
		while (pageObjIt.MoveNext()) {
			if (pageObjIt.GetKey()->GetValue() != "MediaBox") {
				modifiedPageObject->WriteKey(pageObjIt.GetKey()->GetValue());
				copyingContext->CopyDirectObjectAsIs(pageObjIt.GetValue());
			}
		}
		// write new media box
		modifiedPageObject->WriteKey("MediaBox");
		pdfWriter.GetObjectsContext().StartArray();
		pdfWriter.GetObjectsContext().WriteInteger(0);
		pdfWriter.GetObjectsContext().WriteInteger(0);
		pdfWriter.GetObjectsContext().WriteInteger(500);
		pdfWriter.GetObjectsContext().WriteInteger(500);
		pdfWriter.GetObjectsContext().EndArray();
		pdfWriter.GetObjectsContext().EndLine();

		pdfWriter.GetObjectsContext().EndDictionary(modifiedPageObject);
		pdfWriter.GetObjectsContext().EndIndirectObject();

		// cleanup
		delete copyingContext;
	}
```

**Comment by galkahana** [comment]
i'd like to suggest a simpler path.
1. create a target PDF file
2. for each source PDF file:
    2.1 for each such page of the PDF file:
    	2.2.1 page the page dimensions and create a form from the page
    	2.2.2 create a new PDF page in the target PDF at the desired page size
    	2.2.3 create a context for it. place the form at 0,0 location, using a scaling matrix that will resize its dimensions to the target page size dimensions


for 1, you just create a single PDFWriter

for 2, you create a copying context, one at a time for each source file. like this:
```c++
PDFDocumentCopyingContext* copyingContext = pdfWriter.CreatePDFCopyingContext(sourcePDFs[i]);
```

for 2.1, you iterate the source pages, both creating a form for each, and reading its page size. like this:
```c++
PDFParser* parser = GetSourceDocumentParser();
unsigned long pagesCount = parser->GetPagesCount();
for(unsigned long i=0;i<pagesCount;++i) {
	
	// parse dimensions
	PDFPageInput pageInput(parser,parser->ParsePage(i));
	PDFRectangle mediaBox =  pageInput.GetMediaBox();

	// create form
	EStatusCodeAndObjectIDType result = copyingContext->CreateFormXObjectFromPDFPage(i,ePDFPageBoxMediaBox);
	ObjectIDType reusableObjectID = result.second;

	// create target page
	PDFPage* page = new PDFPage();
	page->SetMediaBox(PDFRectangle(0,0,PAGE_WIDTH,PAGE_HEIGHT));

	PageContentContext* pageContent = pdfWriter.StartPageContentContext(page);

	var width = mediaBox.UpperRightX - mediaBox.LowerLeftX;
	var height = mediaBox.UpperRightY - mediaBox.LowerLeftY;

	// place scaled page
	pageContent->q();
	pageContent->cm(PAGE_WIDTH/width,0,0,PAGE_HEIGHT/height,-mediaBox.LowerLeftX,-mediaBox.LowerLeftY);
	pageContent->Do(page->GetResourcesDictionary().AddFormXObjectMapping(reusableObjectID));
	pageContent->Q();	

	pdfWriter.EndPageContentContext(pageContent);
	pdfWriter.WritePageAndRelease(page);
}
```

**Comment by gnat42** [comment]
thank you for such a detailed response. I'll give it a try and respond shortly.

**Comment by gnat42** [comment]
So this code is obviously much cleaner / streamlined than the mess I had. It does resize the page, but not the content (its cut off on the right). There we a few tiny bugs (like using var instead of c types). I'll look a little more closely at the cm() command to see if I can get it working...

This helped me get much much further than I would have been previously. Do you have an amazon wish list or some way I can show a bit of my appreciation for the library and help?

**Comment by gnat42** [comment]
Just wanted to report back that I got this working perfectly because of your sample code. A few tweaks and other 'use case related changes' and its working great. Thanks so much!

Like I said if you have an amazon wish list, or some other way I can show you my gratitude, please let me know.

**Comment by galkahana** [comment]
haha. good to know it worked. cheers
