### ISSUE TITLE
Creating encrypted pdf files

### ISSUE THREAD

**Issue by michaelktree** [galkahana/PDF-Writer#147]
Hi,
My scenario is, I have pdf templates that I modify according to user inputs.
The template pdf files are not encrypted, but I want to return a locked file that cannot be updated  after inserting user data (but I don't want to lock the file with a password).
I am using this command to create a new file, and add to it some fields:

        var pdfWriter = hummus.createWriterToModify(
            new hummus.PDFRStreamForBuffer(pdf_template),
            new hummus.PDFWStreamForFile(tempDirPath + '/dev5.pdf'),            
            {
                userPassword: '',
                ownerPassword: '111',
                userProtectionFlag: 4                   
            }            
        );
: 
: 
: 
        await pdfWriter.writePage(page);
        await pdfWriter.end();

Everything seems to work fine, however the output pdf is not encrypted...

I tried another route to achieve this using "recrypt" function, but that has its own issue:
When using it on an 'existing' file it works fine.
but when using it in the same process, on the output of the createWriterToModify above, I get an exception:
"Unable to recrypt files, check that input and output files are clear and arguments are coool"

Any help would be appreciated.
Thanks,
Michael

**Comment by michaelktree** [comment]
I will close this, and reopen it in hummus repo, I believe it might belong there

**Comment by krunalp1993** [comment]
@michaelktree Did you find any solution for this?

**Comment by michaelktree** [comment]
nope :(
