### ISSUE TITLE
Disable FPU neon optimization on arm64

### ISSUE THREAD

**Issue by kubaroth** [galkahana/PDF-Writer#162]
While building on Jetson Nano I got the following error in libPng:
[ 82%] Linking CXX executable PDFWriterTestPlayground
../LibPng/libLibPng.a(pngrutil.c.o): In function `png_init_filter_functions':
pngrutil.c:(.text+0x748c): undefined reference to `png_init_filter_functions_neon'
collect2: error: ld returned 1 exit status

**Comment by galkahana** [comment]
i think i did
