### ISSUE TITLE
Undefined behaviour and leak in PDFObject.cpp due to delete void*

### ISSUE THREAD

**Issue by misos1** [galkahana/PDF-Writer#166]
```
PDFWriter/PDFObject.cpp:58:3: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
                delete it->second;
                ^      ~~~~~~~~~~
PDFWriter/PDFObject.cpp:98:2: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
        delete result;
```

Delete via void* is undefined behaviour, C++ Standard section 5.3.5/3:

> In the first alternative (delete object), if the static type of the object to be deleted is different from its dynamic type, the static type shall be a base class of the dynamic type of the object to be deleted and the static type shall have a virtual destructor or the behavior is undefined. In the second alternative (delete array) if the dynamic type of the object to be deleted differs from its static type, the behavior is undefined

> 80)This implies that an object cannot be deleted using a pointer of type void* because void is not an object type.

Destructor of your original type will not be called:

[delete Abc*](https://wandbox.org/permlink/dyiiuobnYhdEf7ka)
[delete void*](https://wandbox.org/permlink/QOJeXCwei7QCPojO)

I found one place which uses SetMetadata in DecryptionHelper and sets `new std::list` as metadata which will be leaked because in order to release resources used by `std::list` you need to call its destructor.

**Comment by galkahana** [comment]
i reckon we're good now. a while ago i moved to a proper virtual delete.
