### ISSUE TITLE
Crash / Segfault when parsing PDF files with "Fl" alias for FlateDecode

### ISSUE THREAD

**Issue by thmclellan** [galkahana/PDF-Writer#167]
Using hummus powered by PDF-Writer, our production Node.js app crashed every time we called createReader on a PDF file generated by HP Exstream. Unfortunately it's a sensitive document that can't be shared. 

After troubleshooting with PDFWriter, it turned out that the PDF file was causing an EXC_BAD_ACCESS fault due to a null object in InputStreamSkipperStream.cpp: 

```
bool InputStreamSkipperStream::NotEnded()
{
    return mStream->NotEnded()
}
```
This can be fixed with a null check on mStream, so at least the library won't crash when parsing through a broken PDF.

While investigating how HP Extream encodes their PDFs, it seems they use an alias for FlateDecode of "Fl". See https://github.com/yob/pdf-reader/issues/166 for background.

So to read and modify the HP Extream PDF file, we can add support for the "Fl" alias to PDFParser.cpp line 1928.  

I've got this working now so the HP file can be read and appended.  Fix documented in PR  https://github.com/galkahana/PDF-Writer/pull/168

**Comment by galkahana** [comment]
Thanks. Merged.

**Comment by thmclellan** [comment]
Thank you!
