### ISSUE TITLE
How to compile Code in linux?

### ISSUE THREAD

**Issue by marcus011** [galkahana/PDF-Writer#170]
I have downloaded your library & install it with the mentioned steps 
Now after creating a sample code , I want to know how to compile code in linux with proper linking of library because when I try to compile it I got following errors

> g++ test1.cpp -o test1.o -I/usr/local/include/PDFWriter

```
Errors:
test1.cpp:(.text+0x26): undefined reference to `PDFWriter::PDFWriter()'
test1.cpp:(.text+0x4a5): undefined reference to `PDFWriter::~PDFWriter()'
collect2: error: ld returned 1 exit status
```

**Comment by zvezdochiot** [comment]
@marcus011 say:
>`g++ test1.cpp -o test1.o -I/usr/local/include/PDFWriter`

You need to specify not only the path to include, but also the library itself. Not?

**Comment by marcus011** [comment]
Can you help me out how to do the compilation part

**Comment by marcus011** [comment]
So I tried linking all the *.a files inside build directory and the code got compiled
> g++ test1.cpp -o test.o libPDFWriter.a libFreeType.a libLibJpeg.a libLibAesgm.a  libLibTiff.a libZlib.a libLibPng.a 
So I want to know is this correct way or is there any other way of compiling it?

**Comment by galkahana** [comment]
sounds good. you will need all those libs and deps to  compile the lib.
as a personal favorite, when writing projects i use cmake to do the job, and then it does the building for me.
if you want to see an example of how to use cmake to create an executable with hummus, [this ](https://github.com/galkahana/pdf-text-extraction) is one that i built.
