### ISSUE TITLE
Is it possible to use the PDF-Writer to print a PDF file?

### ISSUE THREAD

**Issue by mbsteixeira** [galkahana/PDF-Writer#174]
O need to print a PDF file and I don't know if the  PDF-Writer  can do that.

**Comment by galkahana** [comment]
Nope. Pdf-writer is a library that cqn create pdf files. It van also parse file and theoritcally speaking you could build something that will render a pdf to ab image ot another ready to print format...but no it camt aemd a pdf file to a printer.
