### ISSUE TITLE
Problem with compile / link in a project with CMake

### ISSUE THREAD

**Issue by stephaneworkspace** [galkahana/PDF-Writer#178]
Hi,

I have a problem with compiling this library in a project.

````
Undefined symbols for architecture x86_64:
  "PDFWriter::PDFWriter()", referenced from:
      create_pdf() in main.cpp.o
  "PDFWriter::~PDFWriter()", referenced from:
      create_pdf() in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
````

The CMakeLists.txt

````
cmake_minimum_required(VERSION 3.22)

project(proj)

set(CMAKE_CXX_STANDARD 20)

ADD_SUBDIRECTORY(PDFWriter4_0)
add_executable(proj main.cpp)
````

The source is in directory ./PDFWriter4_0/ with all the content of release zip

and the main.cpp:
````
#include "PDFWriter4_0/PDFWriter/PDFWriter.h"
#include "PDFWriter4_0/PDFWriter/PDFPage.h"

using namespace proj;

int main() {
    PDFWriter pdfWriter;
    /*pdfWriter.StartPDF("/Users/stephane/Code/CL/C++/astronumerologie-generate/my_pdf.pdf",ePDFVersion13);
    PDFPage* pdfPage = new PDFPage();
    pdfPage->SetMediaBox(PDFRectangle(0,0,595,842));

    /* Add some content for the page */

    /*
    pdfWriter.WritePageAndRelease(pdfPage);
    pdfWriter.EndPDF();*/
}
```

I'm a beginner with CMake. Thanks for making this library.

**Comment by galkahana** [comment]
It's a link error.
You might need some `target_link_libraries` statements there.
Like `target_link_libraries (proj PDFWriter)`.
This should take care of linking.
If you get more dependency issues, then depending on whether they are link or compile, you should add `target_link_libraries` or `include_directories` statements respectively.

As an example, You may consult the project setup in https://github.com/galkahana/pdf-text-extraction and specifically how PDFWriter (and PDFWriter dependencies) is used in https://github.com/galkahana/pdf-text-extraction/blob/master/TextExtraction/CMakeLists.txt. (you probably don't need the use_bidi part so ignore it).

**Comment by stephaneworkspace** [comment]
Thanks for your response, your example work fine
