### ISSUE TITLE
Compilation issues on Windows

### ISSUE THREAD

**Issue by nosleduc** [galkahana/PDF-Writer#197]
Issues occured only on Windows

1)
 I have a compilation issue if I'm trying to use -DUSE_BUNDLED:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON with cmake.
I get the following message LINK : fatal error LNK1181: cannot open input file '..\ZLib\Release\Zlib.lib'
This file does not exist only Zlib.dll exist
The generator is Visual Studio 2022 and I'm using the command line cmake --build . --config Release

2) I have tried to the new way to build PDFWriter with the following cmake command
-DPDFHUMMUS_NO_DCT:BOOL=ON -DPDFHUMMUS_NO_TIFF:BOOL=ON -DPDFHUMMUS_NO_PNG:BOOL=ON -DUSE_BUNDLED:BOOL=OFF -DUSE_UNBUNDLED_FALLBACK_BUNDLED:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON

I have a zlib compiled on my own and it was found correctly. I have also a compilation error

The common problem with these two cases is that when the option -DBUILD_SHARED_LIBS:BOOL=ON the library cannot find the .lib files

**Comment by galkahana** [comment]
I admit to never have tried building shared libraries with (other than once a few years ago). I'll have to check this out. You can try to see if maybe Zlib is compiled into something else (say DLL), then it might be that the test executables or pdfwriter.dll still expects to find a static lib.
In the meantime, if makes sense to your project, compile as static libs.

**Comment by galkahana** [comment]
k. simply put no libs are there cause no symbols are exported. merged a correct and i think you should be fine now.

**Comment by nosleduc** [comment]
If I am using the following options with the latest version in the repository

-DPDFHUMMUS_NO_DCT:BOOL=ON -DPDFHUMMUS_NO_TIFF:BOOL=ON -DPDFHUMMUS_NO_PNG:BOOL=ON -DUSE_BUNDLED:BOOL=OFF -DUSE_UNBUNDLED_FALLBACK_BUNDLED:BOOL=ON 

I still get an error. FreeType does not compile


CMake Error at FreeType/CMakeLists.txt:73 (target_link_libraries):
  Target "FreeType" links to:

    PDFHummus::Zlib

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

**Comment by galkahana** [comment]
cheers. must have missed something. USE_BUNDLED:BOOL=OFF means no pdfhummus::zlib. i probably need a condition somewhere. thanks.

**Comment by galkahana** [comment]
try now. added a condition to use external zlib when its what's compiled against in freetype

**Comment by galkahana** [comment]
we good?

**Comment by galkahana** [comment]
oh sorry for this...and the length of time it seems to take me to deal with it. i'm sure i checked with shared libs on at some iteration but maybe in my later ones i dropped the ball.

not sure i completely understand why, but it seems like linking with aesgm breaks when DLL_IMPORT is defined. 

removed it and linking succeeds. 

I pushed to master this correction. 
Please try again and i hope it will work now.  Please lemme know if it did.

**Comment by nosleduc** [comment]
It works now.

**Comment by galkahana** [comment]
Awesome. Thanks for letting me know
