### ISSUE TITLE
DrawImage from TIFF change image resolution

### ISSUE THREAD

**Issue by AleAsc27** [galkahana/PDF-Writer#204]
I'm trying to draw an image from TIFF to a PDF page. Inside the PDF page, the image has a different resolution (reduced, low quality).
Why? Is there a way to preserve the image resolution and quality?

Here is my code:

            PDFPage *pdfPage = new PDFPage();
            pdfPage->SetMediaBox(PDFRectangle(0, 0, 595, 842)); // A4
            PageContentContext *pageContentContext = pdfWriter->StartPageContentContext(pdfPage);
            AbstractContentContext::ImageOptions opt1 = AbstractContentContext::ImageOptions();
            opt1.fitPolicy = AbstractContentContext::EFitPolicy::eOverflow;
            opt1.imageIndex = pageIdx;
            pageContentContext->DrawImage(0, 0, sourceTif.c_str(), opt1);
            pdfWriter->EndPageContentContext(pageContentContext);
            pdfWriter->WritePage(pdfPage);

**Comment by galkahana** [comment]
oh. you might want to avoid defining a fit policy without also defining bounds (double boundingBoxWidth;, double boundingBoxHeight;) not sure what what's gonna happen then but for the very least is redundant.

**Comment by AleAsc27** [comment]
Thank you. I'll need to use the libTiff to know the real size in cm, right?
I haven't any other fast way, right?

**Comment by galkahana** [comment]
So i reckon thats what hummus does.so not sure if you can fare better. Mind sharing a sample image rhat misbehaves?

**Comment by galkahana** [comment]
But yeah,tou coyld rry this path

**Comment by galkahana** [comment]
If you are looking for an example on how to read image dims from libtiff, and dont feel like digging in hummus code or tiff manuals, a simple example:
https://github.com/galkahana/pdf-transparent-tiff/blob/master/src/lib/ModernTiffImageHandler.cpp#L320

It is also an example of how to recreate transparency in tiff, something that hummus doesnt do natively, but as the example shows something one can extend the lib to do, with the help of using a more simplified api of libtiff .
