### ISSUE TITLE
[Question] - pdf to image

### ISSUE THREAD

**Issue by mohsenomidi** [galkahana/PDF-Writer#206]
Hi all,

Is it possible to convert pdf file to image ?

**Comment by galkahana** [comment]
it is generally possible to do so. that's what PDF interpreters do, and it's potentially possible to implement one with this library, however im positive that there are existing solutions that are ready for you to use. 

I provided some notes about this here:
https://github.com/galkahana/PDF-Writer/issues/200#issuecomment-1463849876
