### ISSUE TITLE
Question about attachments

### ISSUE THREAD

**Issue by tangdouer1005** [galkahana/PDF-Writer#207]
Hello, I want to embed some files as attachments into a pdf through PDF-Writer, I want to know whether PDF-Writer has a corresponding tool, or what tools can support me to accomplish this purpose, and where should I start learning the PDF-Writer library?

**Comment by galkahana** [comment]
PDF-Writer can be used to include file attachments by using its lower level api to create file attachments annotations.
To know how to do this you will need to learn about file attachments annotations in PDF. Look for a PDF reference manual ([1.7](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/pdfreference1.7old.pdf) is what i normally look for) and read the part about file attachments annotations. Then learn about extensibility options in PDF-Writer - https://github.com/galkahana/PDF-Writer/wiki/Extensibility - or start maybe with an example i made once on how to create comment annotations:
https://www.pdfhummus.com/post/45501642143/how-to-extend-the-library-adding-comments-to

**Comment by tangdouer1005** [comment]
> PDF-Writer can be used to include file attachments by using its lower level api to create file attachments annotations. To know how to do this you will need to learn about file attachments annotations in PDF. Look for a PDF reference manual ([1.7](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/pdfreference1.7old.pdf) is what i normally look for) and read the part about file attachments annotations. Then learn about extensibility options in PDF-Writer - https://github.com/galkahana/PDF-Writer/wiki/Extensibility - or start maybe with an example i made once on how to create comment annotations: https://www.pdfhummus.com/post/45501642143/how-to-extend-the-library-adding-comments-to

Thanks for your help, I already know what to do after reading it.
