### ISSUE TITLE
some example projects in wiki are missing

### ISSUE THREAD

**Issue by tangdouer1005** [galkahana/PDF-Writer#208]
like these:

> There are some samples existing in the testing area, for streams usage:
> 
> [BufferedOutputStreamTest](http://github.com/galkahana/PDF-Writer/blob/master/PDFWriterTestPlayground/BufferedOutputStreamTest.cpp) is a short code showing how to use buffered output to an output file stream.
> [FlateEncryptionTest](http://github.com/galkahana/PDF-Writer/blob/master/PDFWriterTestPlayground/FlateEncryptionTest.cpp) is showing a string which is first encoded to flate, and then decoded, using the flate streams.
> [OutputFileStreamTest](http://github.com/galkahana/PDF-Writer/blob/master/PDFWriterTestPlayground/OutputFileStreamTest.cpp) is showing how to write to an output file.
> 

I don't know if there's a way to get it back, or if they're somewhere else now, I'd like to see a few examples.

**Comment by tangdouer1005** [comment]
Sorry, I found their location.

**Comment by galkahana** [comment]
Thanks! i'll correct the documentation
