### ISSUE TITLE
CIDSet encoding does not conform with ISO 19005-2:2011, ISO 19005-3:2012 (PDF/A-2b or PDF/A-3b)

### ISSUE THREAD

**Issue by jacques-quidu** [galkahana/PDF-Writer#216]
Hello,

first thanks for this great C++ library.

I succeeded to implement support in my client application for PDF/A-2b and PDF/A-3b, using PDF-Writer lib:
i have fixed also in my fork the header 4-bytes binary signature, before seeing your similar and recent fix about it.
In order to be fully conforming with PDF/A-2b or PDF/A-3b, i embedded a ICC profile and XMP metadatas as required for PDF/A-2b compliancy, using only the high level methods of the library, which works great. Also embedding all fonts so for PDF/A.

But about font embedding, there is still a remaining issue with some fonts with CIDSet encoding: 
it appears the CIDSet encoding does not conform to PDF/A-2B rule 
https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Parts-2-and-3-rules#rule-62114-4
I have this error with such fonts if embedded:
"Specification: ISO 19005-2:2011, Clause: 6.2.11.4, Test number: 4	
If the FontDescriptor dictionary of an embedded CID font contains a CIDSet stream, then it shall identify all CIDs which are present in the font program, regardless of whether a CID in the font is referenced or used by the PDF or not."

As CIDSet is optional according to the specification, i removed the object and key from font descriptor in order to be conforming to PDF/A-2b in my fork: actually the PDF file is still rendered correct without the CIDSet object and it passes now fully VeraPDF validation for PDF/A-2b so it seems everything is right now.
This workaround seems to be working so with the fonts i tested but i am not sure if it is really safe to juste remove CIDSet object and key from descriptor to fix this issue.

Best regards,

Jacques.

**Comment by jacques-quidu** [comment]
I reproduced this CIDSet PDF/A issue with "Yu Gothic" for instance on Windows.

**Comment by galkahana** [comment]
How about this - please prep a pr and ill look into trying to understand where it might cause trouble.

**Comment by galkahana** [comment]
Also if you have an example that can recreate the issue maybe i can recreate it and figure out if theres something to do about the cid set to correct it

**Comment by galkahana** [comment]
id rather correct it

**Comment by jacques-quidu** [comment]
or as CIDSet is optional according to PDF specification, maybe just providing a PDF option at creation in order to not add /CIDSet would be enough.
Because the requirement which raises the conformance error is not present in PDF/A-1, only starting with PDF/A-2 (Specification: ISO 19005-2:2011, Clause: 6.2.11.4) so the current CIDSet implementation is still legit in PDF 1.3-1.7 or PDF/A-1.

**Comment by galkahana** [comment]
the code intends to do what PDF/A-2 states. at least  this -

"Specification: ISO 19005-2:2011, Clause: 6.2.11.4, Test number: 4
If the FontDescriptor dictionary of an embedded CID font contains a CIDSet stream, then it shall identify all CIDs which are present in the font program, regardless of whether a CID in the font is referenced or used by the PDF or not."

- seems to be what the code does. whatever it is it seems like a bug then and i'd like to fix it.
you are free to do what you will in your fork.

**Comment by galkahana** [comment]
to answer your question RE whether it's safe to remove it, i can't speak for all usages, but im guessing if it's optional and renders well that it's fine to remove it. im not sure what possible side effects might happen, but on its face it seems rather safe. here's the note in the PDF specs:

```
CIDSet
stream
(Optional) A stream identifying which CIDs are present in the CIDFont file. If this entry is present, the CIDFont contains only a subset of the glyphs in the character collection defined by the CIDSystemInfo dictionary. If it is absent, the only indication of a CIDFont subset is the subset tag in the FontName entry (see Section 5.5.3, “Font Subsets”).
The stream’s data is organized as a table of bits indexed by CID. The bits should be stored in bytes with the high-order bit first. Each bit corresponds to a CID. The most significant bit of the first byte corresponds to CID 0, the next bit to CID 1, and so on.
```

**Comment by jacques-quidu** [comment]
yes i read this in the PDF spec too so it is why i thought it would be safe just to remove it ;)
Also i checked with different fonts and same rendering with ou without CIDSet so it seems to be really safe.

Thanks again for this great C++ lib: i like its easy extensibility too.

**Comment by galkahana** [comment]
ok. i am able to recreate the problem and then also understand the problem and generate a working prototype.
i'll have to figure out how to combine it with the rest of the code, but i expect to be able to deliver a working solution with the CID set no later than the weekend.

**Comment by galkahana** [comment]
ok..figured i'll just go ahead and fix it.
Turns out my CIDSet implementation was nowhere near how it should be. omg. not for true type fonts (which Yu Gothic is) nor for otf fonts.  figured out what's actually intended to be the implementation. corrected both cases, and it seems to make https://demo.verapdf.org/ complaints about CIDSet go away.

if you wanna test this, grab the code from master branch (or just change per what's in here - https://github.com/galkahana/PDF-Writer/pull/217) and i think it'll fix the problem on your end too.

**Comment by jacques-quidu** [comment]
Hi thanks for this quick fix:
i will integrate it in my fork asap and try it with my test documents.

Best regards,

Jacques.

**Comment by jacques-quidu** [comment]
Unfortunately the PDF/A-2b conformance error for CIDSet encoding is still present with text in arabic: 
it is not reproducible with latin or hebrew text otherwise (according to my tests).

Well i decided to keep the actual workaround (by removing CIDSet) in my fork as it is safe to remove it (i did not found any issue with my test documents without the CIDSet): the main need for my customer is to able to generate Factur-X or ZugFERD invoices which are based so on PDF/A-3.
And as removing CIDSet reduces also file size (even if very slightly) it is good too for electronic invoices (or for archiving with PDF/A).

**Comment by galkahana** [comment]
This is wierd. Id live to be able to reproduce it. Tried arabic text didnt work. And im fairly sure the solution is good. Ok. Ill try a bit more or wait for recreation method from someone where the workaround isnt good enough. Thanks

**Comment by jacques-quidu** [comment]
i shared a file at this url: [testpublic](https://1drv.ms/f/s!AsgQExzn-1pJgYd2pyg8Bq55fZuJMQ)
it contains a PDF file with text using Segoe UI and part of text in arabic: the font Segoe UI is encoded with CIDSet (using your last fix commit). The file still raises the CIDSet requirement error with VeraPDF.

If i use my workaround by removing the CIDSet the PDF file passes VeraPDF validation.

**Comment by galkahana** [comment]
Thanks man!
and thanks for the workaround

**Comment by jacques-quidu** [comment]
i added in [testpublic](https://1drv.ms/f/s!AsgQExzn-1pJgYd2pyg8Bq55fZuJMQ)
the PDF file version without CIDSet: same rendering so that with the other file but this file testArabicNoCIDSet.pdf passes VeraPDF validation for PDF/A-2b.

**Comment by galkahana** [comment]
oh my. i understand the problem. my solution does not account for something called dependent glyphs, which are used here. ok. i can add something for that. (at this point it's fine if you don't want to test the result haha. i understand that you got a good solution).

**Comment by galkahana** [comment]
This MR - https://github.com/galkahana/PDF-Writer/pull/218 - should take care of this problem.
again, up to you if you want to verify it.

**Comment by jacques-quidu** [comment]
Thanks for fixing again this issue: 
but yes i will stick with my workaround for now which is safe also.

By the way, i found another issue related to copying context: when you append pages from another pdf using a pdf copying context, annotations are lost (like url links - or bookmarks links i implemented in client application using a similar code as for url links by using also pdf annotations): otherwise if you use ModifyPDF (with PDF incremental so), annotations are not lost. So for converting for instance PDF to PDF/A i use ModifyPDF when 4-bytes signature is correct in source file or stream (whick keeps annotations) and a copying context from the source file or stream and then append pages from source when 4-bytes signature is not correct (but with annotations being lost in this case). For now it is fine as i need conversion from PDF to PDF/A only for PDF files generated by the client application (by printing or exported directly) so in this case for now 4-bytes signature in original pdf is always correct and so i can use ModifyPDF which preserves annotations.
But just tell me if you intend to fix this issue too: but you can take your time as for now using ModifyPDF is fine for me ;)

**Comment by jacques-quidu** [comment]
i guess it would need for copying context to copy annotations from source page to DocumentContext::mAnnotations in append pages code before writing page because the write page code assumes annotations to write for page are stored in DocumentContext::mAnnotations ?
