### ISSUE TITLE
annotations are lost with PDFDocumentCopyingContext::AppendPDFPageFromPDF

### ISSUE THREAD

**Issue by jacques-quidu** [galkahana/PDF-Writer#219]
annotations are lost while appending pages with PDFDocumentCopyingContext::AppendPDFPageFromPDF:
it seems like DocumentContext::mAnnotations is not feed from source page to document context before writing the page to destination ?

Note that this issue is not reproducible with PDFWriter::ModifyPDF: it is only reproducible while using a PDFDocumentCopyingContext from a source file or stream returned by PDFWriter::CreatePDFCopyingContext and then append pages from this source context.

i guess it would need for AppendPDFPageFromPDF to copy annotations from source page to DocumentContext::mAnnotations in append pages code before calling write page method because the write page method code assumes annotations to write for page are stored in DocumentContext::mAnnotations.

**Comment by galkahana** [comment]
the basic copy operation copies _only_ the pages and their graphic context, nothing global (and annotations are defined globally). that works as intended. if you do care about annotations, you can extend the copying activity to copy them to.
i wrote a post about this once:
https://www.pdfhummus.com/post/45501619928/copying-pages-with-comments
and here's some sample code:
https://github.com/galkahana/PDFWriterSamples/blob/master/CopyingPagesWithComments/CopyingPagesWithComments.cpp

**Comment by jacques-quidu** [comment]
Ok thanks for the explanation and sample.

**Comment by jacques-quidu** [comment]
actually i wrongly thought that because annotations are referenced in pdf page with /Annots that it should be copied too while copying pages but my mistake so: thanks again.
