### ISSUE TITLE
Publish to github releases without PDFWriterTesting

### ISSUE THREAD

**Issue by darcy-shen** [galkahana/PDF-Writer#243]
There are 118M in `PDFWriterTesting/Materials`, we can publish a tag.gz without the PDFWriterTesting directory to reduce the size of the source code via Github Action.

For example:
```
git archive HEAD . ":(exclude)PDFWriterTesting" -o pdfhummus.tar.gz
```
It will create the tar.gz without PDFWriterTesting on the HEAD, and it is only 3M.

**Comment by galkahana** [comment]
thanks. where would that line go?

**Comment by galkahana** [comment]
I think there's a solution to this problem with .gitattributes:
https://git-scm.com/docs/gitattributes#_export_ignore

lemme try something with that (and also change cmake code to ignore it).

**Comment by galkahana** [comment]
donnow why it keeps auto closing issues...sorry. this is unintentional. i guess cause im mentioning the case.

**Comment by darcy-shen** [comment]
Thanks! The trouble of downloading pdfhummus is pain for me for a long time. The network from/to github is unstable where I live. Before I made a mirror to speed up the download: https://gitee.com/XmacsLabs/pdfhummus
