### ISSUE TITLE
JPEGImageHandler::GetImageDimensions() and pixel density

### ISSUE THREAD

**Issue by TheGS** [galkahana/PDF-Writer#25]
It's not all that clear what units are used for HummusImageInformation::imageWidth and HummusImageInformation::imageHeight... I assume pixels in the case of a bitmap?
I'm calling PDFWriter::GetImageDimensions("path.to.file") to get the image dimensions on a JPEG file that is 300ppi in the JFIF segment.
It looks like JPEGImageHandler::GetImageDimensions() imposes 72ppi on the returned measurement, and this doesn't jive with what's actually in the placed ImageXObject itself (SamplesWidth and SamplesHeight) when written by JPEGImageHandler::CreateAndWriteImageXObjectFromJPGInformation().

**Comment by galkahana** [comment]
what's returned is points, which is 1/72 of an inch. physical size.
samplewidth/sampleheight would be pixels.

**Comment by TheGS** [comment]
ah, thanks

**Comment by TheGS** [comment]
Image coordinate system is defined in terms of samples, so for a JPEG where we have to perform further transformations, will will have to call JPEGImageHandler::RetrieveImageInformation() to get the appropriate SamplesWidth and SamplesHeight.  Do I understand that correctly?

**Comment by galkahana** [comment]
correct
