### ISSUE TITLE
Fail to draw rectangle to pdf,if rectangle larger than(595x842)

### ISSUE THREAD

**Issue by HaerBugMaker** [galkahana/PDF-Writer#250]
I want to modify pdf,just draw a rectangle,but if it's size larger than 595x842,only show the part 595x842
here is my code

**PDFWriter *pdfWriter = new PDFWriter;
pdfWriter->ModifyPDF("/root/pdf/wsxx_2.pdf",ePDFVersion13,"/root/pdf/wsxx_2_out.pdf");
PDFModifiedPage modifiedPage(pdfWriter,0);
AbstractContentContext* contentContext = modifiedPage.StartContentContext();
AbstractContentContext::GraphicOptions pathFillOptions(AbstractContentContext::eFill,
                                                                AbstractContentContext::eCMYK,
                                                                0xFF00FF00);
contentContext->DrawRectangle(0,0,595,842,pathFillOptions);
modifiedPage.EndContentContext();
modifiedPage.WritePage();
pdfWriter->EndPDF();
delete pdfWriter;** 

here is the result
![~ 5Q646{D4GTGA3R@IL4@BW](https://github.com/galkahana/PDF-Writer/assets/34954344/01ee1366-fb6f-4d35-b11c-61214ad13436)

**Comment by galkahana** [comment]
Perhaps theres clipping artifacts from the original page. Try reviewing the pdf code of the page.

Or juat add a 3rd parameter to pdfmodified page constructor call with "true". This should encapsulate the graphics drawn by the oroginal page woth save and restore and any side effects to the graphics will be void for the graphics you draw

**Comment by HaerBugMaker** [comment]
It works! Thank you very much!! hahaha :)
