### ISSUE TITLE
Double hex encoding in AbstractContentContext::TJHexLow

### ISSUE THREAD

**Issue by stribor** [galkahana/PDF-Writer#253]
I was calling following method:
 `AbstractContentContext::TJ(const GlyphUnicodeMappingListOrDoubleList& inStringsAndSpacing)`

and it already converts string to hex in:

https://github.com/galkahana/PDF-Writer/blob/217369c46d68cd04c94d20ca93bad65026e88dd0/PDFWriter/AbstractContentContext.cpp#L1247-L1251

and then calls `AbstractContentContext::TJHexLow` which again re-encodes already encoded string to hex breaking generated PDF

https://github.com/galkahana/PDF-Writer/blob/217369c46d68cd04c94d20ca93bad65026e88dd0/PDFWriter/AbstractContentContext.cpp#L974 should actually be `mPrimitiveWriter.WriteEncodedHexString(it->SomeValue);`

**Comment by galkahana** [comment]
oh my.
thanks :)

turns out fixing a similar issue in Tj (and other friends) [a few years back](https://github.com/galkahana/PDF-Writer/commit/99c1d9a37f0628ff63c2ed249464707c3bcc0175) i neglected to do the same for TJ.

Will fix in a bit

**Comment by galkahana** [comment]
merged a correction

**Comment by stribor** [comment]
Works fine now 👍
