### ISSUE TITLE
Failure in JPGParser while parsing specific JPG  

### ISSUE THREAD

**Issue by hadasg** [galkahana/PDF-Writer#26]
Hi Gal,

Running the function PDFWriter::CreateImageXObjectFromJPGFile with specific JPG returns failure.
When debugging I realized that the problem is in the function JPEGImageParser::ReadPhotoshopData, it seems that when resolutionBim not found there is an exceeding in the read bytes.
I added some validation tests that seems to solve the problem, below is the function after my changes:
EStatusCode JPEGImageParser::ReadPhotoshopData(JPEGImageInformation& outImageInformation,bool outPhotoshopDataOK)
{
	EStatusCode status;
	unsigned int intSkip;
	unsigned long toSkip;
	unsigned int nameSkip;
	unsigned long dataLength;
	bool resolutionBimNotFound = true;

	do {
		status = ReadIntValue(intSkip);
		if(status != PDFHummus::eSuccess)
			break;
		toSkip = intSkip-2;
		status = SkipTillChar(scEOS,toSkip);
		if(status != PDFHummus::eSuccess)
			break;
		while(toSkip > 0 && resolutionBimNotFound)
		{
			status = ReadStreamToBuffer(4);
			if(status !=PDFHummus::eSuccess)
				break;
            toSkip-=4;
            if(0 != memcmp(mReadBuffer,sc8Bim,4))
                break; // k. corrupt header. stop here and just skip the next
			status = ReadStreamToBuffer(3);
			if(status !=PDFHummus::eSuccess)
				break;
			toSkip-=3;
			nameSkip = (int)mReadBuffer[2];
			if(nameSkip % 2 == 0)
				++nameSkip;
			SkipStream(nameSkip);
			toSkip-=nameSkip;
			resolutionBimNotFound = (0 != memcmp(mReadBuffer,scResolutionBIMID,2));
			status = ReadLongValue(dataLength);
			if(status != PDFHummus::eSuccess)
				break;
			toSkip-=4;
			if(resolutionBimNotFound)
			{
				if(dataLength % 2 == 1)
					++dataLength;
				toSkip-=dataLength;
				SkipStream(dataLength);
			}
			else
			{
				status = ReadStreamToBuffer(16);
				if(status !=PDFHummus::eSuccess)
					break;
				toSkip-=16;
				outImageInformation.PhotoshopInformationExists = true;
				outImageInformation.PhotoshopXDensity = GetIntValue(mReadBuffer) + GetFractValue(mReadBuffer + 2);
				outImageInformation.PhotoshopYDensity = GetIntValue(mReadBuffer + 8) + GetFractValue(mReadBuffer + 10);
			}
		}
		if(PDFHummus::eSuccess == status)
			SkipStream(toSkip);
	}while(false);
    outPhotoshopDataOK = !resolutionBimNotFound;
	return status;
}

What do you think?

Attached is the problematic JPG.
![32degrees_2](https://cloud.githubusercontent.com/assets/5138698/9228121/a889ff68-411f-11e5-96b9-63d581d3ea53.jpg)

Thanks,
Hadas

**Comment by hadasg** [comment]
Unintentionally I sent you the original code, below is the code after my changes:
EStatusCode JPEGImageParser::ReadPhotoshopData(JPEGImageInformation& outImageInformation,bool outPhotoshopDataOK)
{
	EStatusCode status;
	unsigned int intSkip;
	unsigned long toSkip;
	unsigned int nameSkip;
	unsigned long dataLength;
	bool resolutionBimNotFound = true;

	do {
		status = ReadIntValue(intSkip);
		if(status != PDFHummus::eSuccess)
			break;
		toSkip = intSkip-2;
		status = SkipTillChar(scEOS,toSkip);
		if(status != PDFHummus::eSuccess)
			break;
		while(toSkip > 0 && resolutionBimNotFound)
		{
			if (toSkip < 4)
				break;
			status = ReadStreamToBuffer(4);
			if(status !=PDFHummus::eSuccess)
				break;
            toSkip-=4;
            if(0 != memcmp(mReadBuffer,sc8Bim,4))
                break; // k. corrupt header. stop here and just skip the next
			if (toSkip < 3)
				break;
			status = ReadStreamToBuffer(3);
			if(status !=PDFHummus::eSuccess)
				break;
			toSkip-=3;
			nameSkip = (int)mReadBuffer[2];
			if(nameSkip % 2 == 0)
				++nameSkip;
			if (toSkip < nameSkip)
				break;
			SkipStream(nameSkip);
			toSkip-=nameSkip;
			resolutionBimNotFound = (0 != memcmp(mReadBuffer,scResolutionBIMID,2));
			if (toSkip < 4)
				break;
			status = ReadLongValue(dataLength);
			if(status != PDFHummus::eSuccess)
				break;
			toSkip-=4;
			if(resolutionBimNotFound)
			{
				if(dataLength % 2 == 1)
					++dataLength;
				if (toSkip < dataLength)
					break;
				toSkip-=dataLength;
				SkipStream(dataLength);
			}
			else
			{
				if (toSkip < 16)
					break;
				status = ReadStreamToBuffer(16);
				if(status !=PDFHummus::eSuccess)
					break;
				toSkip-=16;
				outImageInformation.PhotoshopInformationExists = true;
				outImageInformation.PhotoshopXDensity = GetIntValue(mReadBuffer) + GetFractValue(mReadBuffer + 2);
				outImageInformation.PhotoshopYDensity = GetIntValue(mReadBuffer + 8) + GetFractValue(mReadBuffer + 10);
			}
		}
		if(PDFHummus::eSuccess == status)
			SkipStream(toSkip);
	}while(false);
    outPhotoshopDataOK = !resolutionBimNotFound;
	return status;
}

**Comment by galkahana** [comment]
Hi Hadas,
seems good. i'll take it.

Thanks.
Gal.


ps. mazel tov.

**Comment by hadasg** [comment]
Thanks :)

**Comment by hadasg** [comment]
Below is the final code - I changed the code to return false in the out parameter "outPhotoshopDataOK" in case of failure.

EStatusCode JPEGImageParser::ReadPhotoshopData(JPEGImageInformation& outImageInformation,bool outPhotoshopDataOK)
{
	EStatusCode status;
	unsigned int intSkip;
	unsigned long toSkip;
	unsigned int nameSkip;
	unsigned long dataLength;
	bool resolutionBimNotFound = true;

	do {
		status = ReadIntValue(intSkip);
		if(status != PDFHummus::eSuccess)
			break;
		toSkip = intSkip-2;
		status = SkipTillChar(scEOS,toSkip);
		if(status != PDFHummus::eSuccess)
			break;
		while(toSkip > 0 && resolutionBimNotFound)
		{
			if (toSkip < 4)
				break;
			status = ReadStreamToBuffer(4);
			if(status !=PDFHummus::eSuccess)
				break;
            toSkip-=4;
            if(0 != memcmp(mReadBuffer,sc8Bim,4))
                break; // k. corrupt header. stop here and just skip the next
			if (toSkip < 3)
				break;
			status = ReadStreamToBuffer(3);
			if(status !=PDFHummus::eSuccess)
				break;
			toSkip-=3;
			nameSkip = (int)mReadBuffer[2];
			if(nameSkip % 2 == 0)
				++nameSkip;
			if (toSkip < nameSkip)
				break;
			SkipStream(nameSkip);
			toSkip-=nameSkip;
			resolutionBimNotFound = (0 != memcmp(mReadBuffer,scResolutionBIMID,2));
			if (toSkip < 4)
			{
				resolutionBimNotFound = true;
				break;
			}
			status = ReadLongValue(dataLength);
			if (status != PDFHummus::eSuccess)
			{
				resolutionBimNotFound = true;
				break;
			}
			toSkip-=4;
			if(resolutionBimNotFound)
			{
				if(dataLength % 2 == 1)
					++dataLength;
				if (toSkip < dataLength)
					break;
				toSkip-=dataLength;
				SkipStream(dataLength);
			}
			else
			{
				if (toSkip < 16)
				{
					resolutionBimNotFound = true;
					break;
				}
				status = ReadStreamToBuffer(16);
				if(status !=PDFHummus::eSuccess)
				{
					resolutionBimNotFound = true;
					break;
				}
				toSkip-=16;
				outImageInformation.PhotoshopInformationExists = true;
				outImageInformation.PhotoshopXDensity = GetIntValue(mReadBuffer) + GetFractValue(mReadBuffer + 2);
				outImageInformation.PhotoshopYDensity = GetIntValue(mReadBuffer + 8) + GetFractValue(mReadBuffer + 10);
			}
		}
		if(PDFHummus::eSuccess == status)
			SkipStream(toSkip);
	}while(false);
    outPhotoshopDataOK = !resolutionBimNotFound;
	return status;
}

**Comment by galkahana** [comment]
Hi Hadas,
well i figured that the code looks a little bit cluttered with all those checks. I figured the spirit of the solution has to be with - if there's a read error fail the whole process, if there's not enough to read than just ignore this photoshop data.

This led me to rewrite this method a bit. you can see the end result in what i checked in right now here:
https://github.com/galkahana/PDF-Writer/blob/master/PDFWriter/JPEGImageParser.cpp#L283

the code is refactored to let subroutines deal with checking whether there's enough to read, do the read and reduce the accumulated bytes to skip. The result is cleaner code, having the same amount of conditionals as the original.
I think it still maintains the same gist of things.
let me know what you think.

Gal.

**Comment by hadasg** [comment]
Hi Gal,

It's look good and cleaner.

Thanks,
Hadas
