### ISSUE TITLE
PDFParser::ParseFileDirectory,Unexpected object at xref start

### ISSUE THREAD

**Issue by huangtiansama** [galkahana/PDF-Writer#274]
I need to parse a PDF file, but it fails to parse
![image](https://github.com/user-attachments/assets/daeb0e4b-2066-4486-84b1-9bd171bfc54e)
![image](https://github.com/user-attachments/assets/29d8b390-e5dd-45ad-a981-a2da9c53289e)
![image](https://github.com/user-attachments/assets/c330a2ed-0b19-4922-91c5-045a05299035)

**Comment by galkahana** [comment]
Hi huangtiansama, care to share the pdf so i can figure out why the xref start os read incorrectly?

**Comment by huangtiansama** [comment]
> Hi huangtiansama, care to share the pdf so i can figure out why the xref start os read incorrectly?

OK, but you need to wait Monday

**Comment by galkahana** [comment]
Sure, no problem. Thank you :)

**Comment by huangtiansama** [comment]
> Sure, no problem. Thank you :)

![image](https://github.com/user-attachments/assets/fc8d150c-53c6-4cfb-a215-a1b81531beef)
sorry, This file is too large
I've tried some solutions that jump 8 bytes after "endobj" and so far, it works fine
![image](https://github.com/user-attachments/assets/c0cb6d86-e111-4afc-b6f7-d97e7f5ec9fc)

![image](https://github.com/user-attachments/assets/71f740db-054a-4a97-a53c-3ddfbff19b59)

**Comment by galkahana** [comment]
Well could also contact whoevers created the pdf and tell them they create faulty ones.
Is this loading on acrobat?

**Comment by galkahana** [comment]
Wanna try sending to me via email? Gal.kahana@hotmail.com

**Comment by huangtiansama** [comment]
> Wanna try sending to me via email? [Gal.kahana@hotmail.com](mailto:Gal.kahana@hotmail.com)

OK, the email has been sent

**Comment by galkahana** [comment]
ok. looks to be like a consistent 8 byte offset here.
normally i'd tell you to go back to whoever created that PDF and get them to fix the position...which you probably should anyways if you can.
Still. seems like i can create a fairly safe solution so that it's both not horribly unsafe  and seems to read the file ok.
implemented here - https://github.com/galkahana/PDF-Writer/pull/277.
if works for you, i can incorporate in the main branch

**Comment by galkahana** [comment]
the solution didn't work. parts of the xref do point to the right positions. this PDF need to be corrected (adobe acrobat can be used for that, by opening and closing). then it can be used with this library
