### ISSUE TITLE
Question :Resize PDF with many different sizes, is this possible?

### ISSUE THREAD

**Issue by vegarringdal** [galkahana/PDF-Writer#29]
Is it possible to read a PDF file containing pages of different sizes and set them all to A4 size without loosing markups etc?

**Comment by galkahana** [comment]
Yes. Open the pdf file for modification and change each page object to be the same with resect to all keys but the page size (via media box). Copy all keys/values but media box, and add it setting its value to the desired page size

**Comment by vegarringdal** [comment]
Great, thanks for the fast reply.
Pretty new when it comes to c++, but got one of the samples working now, so how hard can it be.. hehe :-)

**Comment by vegarringdal** [comment]
Been trying the merging helper and other stuff to try and understand it.
Took and created a sample file, and added some markup to it with acrobat.
But when I merge that into a new file the markup is gone, maybe Im missing something?
Thanks

This is the file I tried to make a copy of:
https://dl.dropboxusercontent.com/u/23375256/testPage.pdf

```
//create writer/set file to write to
PDFWriter pdfWriter;
pdfWriter.StartPDF(scBasePath +"testpageCopy.pdf", ePDFVersion13);

//create page
PDFPage* page = new PDFPage();
page->SetMediaBox(PDFRectangle(0, 0, 595, 842));

//merge testpage into the into new one
PDFPageMergingHelper(page).MergePageContent(&pdfWriter, scBasePath + "testpage.pdf", 0);
pdfWriter.WritePageAndRelease(page);

//close
pdfWriter.EndPDF();

return 0;
```

**Comment by galkahana** [comment]
copying would lose most markup but content. there's method to improve that.
but the path that i think that you should take is to actually create a modified version of the original.
i'll write the script and post it soon

**Comment by galkahana** [comment]
actually turns out i already have an example. see here:https://github.com/galkahana/PDF-Writer/blob/master/PDFWriterTestPlayground/ModifyingExistingFileContent.cpp#L95

Let me know if this helps.

Gal.

**Comment by vegarringdal** [comment]
ok, will have a look at that, for the resizing part.
But merging 2 or more pages with markup, is there a good way to do that?
You said in the first reply that there is a method to improve that :-)

**Comment by galkahana** [comment]
the markups that you added are annotations. the default method copies only the contents streams and media boxes. you can use a hook to copy also the annotations, i wrote about it here:
http://pdfhummus.com/post/45501619928/copying-pages-with-comments

in your case use MergePageContent instead of AppendPDFPageFromPDF, cause you want to set the page box, but the principal of hooking to the final page write is the same.

still...the method of modification should be significantly simpler and safer, taking care of all features of a page, as well as global PDF level features, as you are just modifying the existing PDF.

Gal.

**Comment by vegarringdal** [comment]
Last sample worked great, but see I need to dig more into the documentation, and learn more c++:-)
Thanks for the help and a huge thanks for making this library.
