### ISSUE TITLE
A space character will produce a warning | 一个空格字符会产生警告

### ISSUE THREAD

**Issue by YLXDXX** [galkahana/PDF-Writer#292]
When I write a string containing only one space in a PDF file, such as `std::string test=" ";`, it can be written normally, but the PDF browser will report a warning message:
`[w] unknown keyword: "inf`
When I use a string with two spaces, such as `std::string test=" ";`, or other single characters, this warning message disappears.
The PDF browser I use is `llpp`.

当我在PDF文件中写入的字符串仅包含一个空格时，如 `std::string  test=" ";`，可以正常写入，但是PDF浏览器会报一个警告信息：
`[w] unknown keyword: "inf`
当我使用两个空格字符串，如`std::string  test="  ";` ，或者其它单一字符，此警告信息会消失。
我使用的PDF浏览器为 `llpp`。

![2024-12-14_17-52](https://github.com/user-attachments/assets/e6749ae0-6918-46c9-addd-928c79881c13)

> Sorry for the poor English, used Google Translate.

**Comment by galkahana** [comment]
No worries. I'm not sure i can understand the problem though. specifically what method do you provide the test string to?

Could you please provide short code program that can recreate the problem? perhaps in the form of a test like any one of the files in PDFWriterTesting?

In addition, or alternatively provide an example PDF that shows the failure?

**Comment by YLXDXX** [comment]
Hi, I found the problem. I first used `CalculateTextDimensions` to calculate the height and width of the string, and then did some calculations based on the result to get the font size I wanted. When the string only contains one space, the result calculated by `CalculateTextDimensions` has a problem, and all the results are zero. So there is a division by zero in my program to calculate the font size, and the result is 'inf`, that is, `pageContentContext->Tf(fontTTF, inf);`, so there is the warning message of the PDF browser above.

```
#include "PDFWriter/PDFWriter.h"
#include "PDFWriter/PDFUsedFont.h"
#include <iostream>

static const std::string scBasePath =  "/somewhere";

int main(int argc, char* argv[])
{
    PDFWriter pdfWriter;
    
    PDFUsedFont* fontTTF = pdfWriter.GetFontForFile(scBasePath + "some.ttf");
    PDFUsedFont::TextMeasures D;
    
    std::string tt_1=" "; //one space
    std::string tt_2="  "; //two space
    
    D = fontTTF->CalculateTextDimensions(tt_1,14);
    std::cout << "one space: width " << D.width << ", height " << D.height << ", xMin "  << D.xMin 
              << ", xMax " << D.xMax << ", yMin " << D.yMin << ", yMax " << D.yMax << std::endl;
    
    D = fontTTF->CalculateTextDimensions(tt_2,14);
    std::cout << "two space: width " << D.width << ", height " << D.height << ", xMin "  << D.xMin 
              << ", xMax " << D.xMax << ", yMin " << D.yMin << ", yMax " << D.yMax << std::endl;
    
    return 0;
}
```

In the above program, `CalculateTextDimensions` gives an incorrect result of all zeros for a space:
```
one space: width 0, height 0, xMin 0, xMax 0, yMin 0, yMax 0
two space: width 3.626, height 0, xMin 0, xMax 3.626, yMin 0, yMax 0
```

**Comment by galkahana** [comment]
Thanks. Do you have the font file you have been using? I suspect that theres no width for space and what you do see is just default space between chars. I can verify with the font file.

**Comment by YLXDXX** [comment]
I tried five fonts, all with the same problem, you can check, thanks.
[fonts.tar.gz](https://github.com/user-attachments/files/18139364/fonts.tar.gz)

**Comment by galkahana** [comment]
Hi,
what you are seeing here is that space in itself does not have a width. which is why you are getting 0. What it does have is an "advance", which is the position where a next character should be placed. this is the 3.626 measure that you are seeing. Depending on what you are doing, this might be the measure you are looking for.

For example, if you are trying to determine where to place the next text, you will want to use both `CalculateTextDimensions` and `CalculateTextAdvance` of PDFUsedFont. by summing them up, you can determine what's the position of a following text.

However, if you are trying to wrap the text in a frame, then CalculateTextDimensions() is what you need. In the case of a single space it'll be a 0 width box as space does not draw anything and so does not have width.

**Comment by YLXDXX** [comment]
Thank you very much for your reply, which helped me understand the problem.
