### ISSUE TITLE
[Question] How to set the Font in a FreeText annotation ?

### ISSUE THREAD

**Issue by magicboker** [galkahana/PDF-Writer#30]
I tried to use your library to create a FreeText annotation (Subtype = FreeText).
So far everything went well, but to set the font, i followed the PDF spec to set
the "DA" field as FontName FontSize "Tf" Red Green Blue "rg"
In the spec, it said FontName should be the key (or name) to the Font dictionary.
Do you know to implement this by using your library?
I checked the PDFUsedFont class and i can load any font file, but how can i write the selected font to the Font dictionary for a "FreeText" annotation?
Thank you very much for creating the great library and helping answer the question!!

**Comment by galkahana** [comment]
I have no idea. seriously.
I'm not sure that you can actually use Tf in such a context.

Specifically i don't see a resources dictionary reference here that you coud hang a font definition on.
If you would, i would tell you to simply follow AbstractContentContext::WriteText and figure out what you need from there (https://github.com/galkahana/PDF-Writer/blob/master/PDFWriter/AbstractContentContext.cpp#L1409)

but what will you do with the font that you get? i see no resources dictionary here.

donnow.

**Comment by magicboker** [comment]
In the pdf spec: page 679 in ([pdf_reference_1-7.pdf](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf))

The default appearance string (DA) contains any graphics state or text state oper- ators needed to establish the graphics state parameters, such as text size and color, for displaying the field’s variable text. Only operators that are allowed within text objects may occur in this string (see Figure 4.1 on page 197). At a minimum, the string must include a Tf (text font) operator along with its two operands, font and size. The specified font value must match a resource name in the Font entry of the default resource dictionary (referenced from the DR entry of the interactive form dictionary; see Table 8.67). A zero value for size means that the font is to be auto- sized: its size is computed as a function of the height of the annotation rectangle.

**Comment by galkahana** [comment]
well, that's true for form. but what about text free annotation?

**Comment by magicboker** [comment]
DA is the required field in FreeText annotation to set font name, size, and text color.
In the 
![example](https://dl.dropboxusercontent.com/u/21305787/pdf_annotation_freetext_table_8_25.png)
