### ISSUE TITLE
Failing playgroundtest on linux(ubuntu) due to inconsistency in filename/directory cases

### ISSUE THREAD

**Issue by fyt000** [galkahana/PDF-Writer#31]
Linux filesystem is case-sensitive but in playgroundtest some file directory's cases does not match the actual file/directory. Its not really an issue or anything...I just had to check the .log and manually fix some of the names. I guess I will report it in case someone else is wondering why some of the tests failed to save them some time.

**Comment by galkahana** [comment]
Was solved
