### ISSUE TITLE
Embedded LinuxLibertine OpenType fonts come out totally messed up

### ISSUE THREAD

**Issue by stribor** [galkahana/PDF-Writer#33]
I was trying to embed some otf fonts i.e. Linux Libertine otf fonts (I got them form http://www.linuxlibertine.org/ )
Since font looks ok elsewhere I'm assuming something goes wrong with font embedding
Here is actuall Hello World otuput I get with LinLibertine_R.otf font:

![linlibertine_r otf](https://cloud.githubusercontent.com/assets/1141923/12653456/f2be4e9a-c5ef-11e5-9bf6-25c5e79a071c.png)

Looks like curve control points got treated like actual points or cubic vs quad curves are messed up while converting path or something like that happens.

**Comment by galkahana** [comment]
Bummer. otf supposed to be rather straightforward passthrough.
Try convertig the font to propper true type (ttf), and see if it solves the problem.

If you want to have an attempt at debugging, I can provide pointers.

Gal.

**Comment by stribor** [comment]
This is problem at end user side.

So I would like any help I could get to try to debug this issue.

**Comment by galkahana** [comment]
Cool.
The relevant element that writes the glyph data for open types is `CharStringType2Flattener::WriteFlattenedGlyphProgram`
This method iterates the original glyph drawing commands, for the case of Open Type CFFs and writes them to the source. It pretty much passes through the elements, as PDF uses the same CFF data internally. The only thing it does is to flatten the font program, which is the same thing that everybody does.
What we expect is that there is a bug in one of the passthroughs. probably som mixup with the operators order.

The easiest way to figure out what's wrong is to create a PDF from an application that does it correctly with only one letter. Then do it with hummus.
Then compare the glyph data, and see where the instructions differ. then debug `CharStringType2Flattener::WriteFlattenedGlyphProgram` and see at what point it started to deviate and try to figure out why.

You'll have to get the font definition from both PDFs. after that you can use ttx or hummus CharStringType2Tracer to get a human readable form of the glyph instructions.

To extract the fotn definition you can use hummus parsing tools. just locate the embedded font program. it will be pointed to by the font descriptor FontFile3 key.

Another option is to just go through `CharStringType2Flattener::WriteFlattenedGlyphProgram` and try to figure out if it does something out of the ordinary, but without reference that works it may be difficult. but this path also require less preparation. so you can start with this...see if you can figure this out already from there, and possibly get lucky.

Gal.

**Comment by galkahana** [comment]
@stribor good news.
Got some time, and found and corrected the issue. you can see the commit here (the latest):
https://github.com/galkahana/PDF-Writer/commit/f1780012089e7afdcccbe74af0e12d0bd29bbfd0

Gal.

**Comment by stribor** [comment]
Perfect, thank you. I started finding some time to look into it :)
