### ISSUE TITLE
Problematic sanity check in OpenTypeFileInput.cpp OpenTypeFileInput::ReadOpenTypeSFNTFromDfont() leads to problems embedding .dfont fonts on El Capitan

### ISSUE THREAD

**Issue by TheGS** [galkahana/PDF-Writer#36]
There is an sanity check in OpenTypeFileInput::ReadOpenTypeSFNTFromDfont() that results in failures embedding some fonts that are packaged as .dfont files on Mac OS X 10.11 El Capitan.

I believe there has been a misreading of the Inside Mac documentation for the resource fork format, where the space reserved in the resource map header on disk for a copy of the resource file header when in memory is assumed to actually be a bitwise copy of the resource file header on disk. the diagram of the format of the resource map in Inside Mac labels this field as "Reserved for a copy of the resource header", and the text actually says, "After reading the resource map into memory, the Resource Manager stores the indicated information in the reserved areas at the beginning of the map."

```C++
{
	// check that the two headers match

	int allzeros = 1, allmatch = 1;
	for (int i = 0; i < 16; ++i )
	{
		if ( head[i] != 0 ) allzeros = 0;
		if ( head2[i] != head[i] ) allmatch = 0;
	}
	if ( !allzeros && !allmatch ) return PDFHummus::eFailure;
}
```

For example, the data-fork-based resource file /System/Library/Fonts/Geneva.dfont does happen to pass this sanity check on Yosemite, but the version that comes with El Capitan does not. And this means that an attempt to embed the Geneva font will fail on a stock El Capitan system because the reader bails since the resource file header does not match whatever bytes happen to be in the space reserved for the in-memory copy

Removing this check lets us successfully embed the Geneva font (and some other fonts housed in .dfont files) on Mac OS X 10.11 El Capitan.

There is also another sanity check which may be problematic...

```C++
        if ( rdata_pos + rdata_len != map_pos || map_pos == 0 ) {
            return PDFHummus::eFailure;
        }
```

The documentation in Inside Mac does not guarantee that the resource map is exactly positioned immediately after the resource data (i.e. it is not guaranteed by the documentation that `rdata_post+rdata_len == map_pos`). Having two separate offset fields allows the data structures to appear in any order on disk, and with any number of (possibly non-zero) bytes padding the gap between them. For example, a quick way for the Resource Manager to update the resource map for a resource file on disk might be to simply append a brand new resource map to the end of the file, and then update the header to point to the new one, leaving the old one in place.

**Comment by galkahana** [comment]
Makes sense.
sounds like the major part of testing here is to figure out they really got a mac resource file.
can this be taken care of without these tests?

Gal.

**Comment by TheGS** [comment]
A resource-based font packaged in resources in the data fork (as opposed to the traditional resource fork of classic Mac font suitcases) will always have the filename extension ".dfont".  For fonts, we can assume that if the filename ends with ".dfont", and the header values at the beginning of the file look sane (according to documentation and common sense), and the parsed resource map has entries for the 'sfnt' resource(s) we're looking for, and the metadata (offset, length, etc.) for those resources look sane, then we can load the 'sfnt' container(s) from those resources.

**Comment by galkahana** [comment]
Sounds good. i reckon if i can get to sfnt that should be fine, so just be careful with reading etc. comment out and be careful with reading.

k.
I'll try to get to this soon. 
i welcome pull requests :) too.

Gal.

**Comment by galkahana** [comment]
checked in [commit](https://github.com/galkahana/PDF-Writer/commit/bbe02a673a3b58028c6efabe7a7dc89a4ba9b17e) which has a safe read of the font file, while avoiding the problematic tests
