### ISSUE TITLE
[Question] How to modify all pages' "Parent" to the new Page Tree node?

### ISSUE THREAD

**Issue by magicboker** [galkahana/PDF-Writer#42]
How to modify all pages' "Parent" to the new page tree node?
Calling WritePagesTree() to create a new page tree node, but how to modify existing pages to re-parent them to the new page tree node?

**Comment by raimundomartins** [comment]
Have you tried fetching the page's dictionary, changing the "Parent" object, and re-write the pages?

**Comment by galkahana** [comment]
i'll respond in that other question, but basically what @raimundomartins said.

**Comment by magicboker** [comment]
Is there available API to get it done? or do i need to parse page > get page dict, copy all attributes except "parent", and modify the parent attribute > write to context >....etc. all done by hand craft codes by ourself ?

**Comment by galkahana** [comment]
yourself man. see #27

**Comment by magicboker** [comment]
thank you very much!
I'm reading your new solutions there.
