### ISSUE TITLE
Typo in test in CFFFileInput::ReadEncoding()

### ISSUE THREAD

**Issue by TheGS** [galkahana/PDF-Writer#44]
On line 847 of CFFFileInput.cpp, in the function CFFFileInput::ReadEncoding(), there is a logic error. The code is intended to check if the high bit of an 8-bit byte is set, but the condition actually tested `((encodingFormat & 0x80) == 1)` will always be false.  That should probably read `((encodingFormat & 0x80) != 0)`, instead (or any number of ways to correctly test only that bit).
I'm sorry, but for a number of reasons, I can't fork the project and submit a pull request with a simple fix; right now, the best I can do is alert that there is an issue.

**Comment by galkahana** [comment]
That's good enough :)
i'll look into it. Thank you.
