### ISSUE TITLE
[Question] How to add LZWDecode support?

### ISSUE THREAD

**Issue by magicboker** [galkahana/PDF-Writer#45]
Failed in an invocation to copyingContext->AppendPDFPageFromPDF(pageIndex) --> calling PDFParser::CreateFilterForStream to parse a PDF page and failed: the log showed "PDFParser::CreateFilterForStream, supporting only flate decode and ascii 85 decode, failing".
Then, i found the PDF using LZWDecode.
It seemed this SDK doesn't support LZWDecode, am i right?
If so, how to add LZWDecode support by myself?
PS: if it's not easy to add LZWDecode filter support, how can i copy pages from one PDF to the other PDF without involving the unsupported filter support?

**Comment by galkahana** [comment]
tell you the truth, looking at the code, i'm not sure that decoding is required here, so the filtering should be skipped, and stream copied as is.
copying only require the decryption of streams for some scenarios, which is not this one (just appending the page). the lib can blindly copy the stream and that it.

That's the best solution quite clearly. it's the fastest and less sophisticated, and so can fit for more PDF types.

Implementing lzwdecode shouldn't be too hard. you need to implement an IByteReader object that can read lzw (look at InputAscii85DecodeStream for an example for ascii85 decoding) and then add an option in PDFParser::CreateFilterForStream to provide it per the filter name value (there might be some parameters specific to lzw decoding, they can be retrievied through the inDecodeParams value). The PDF reference has an explanation of lzw encoding that can be probably used for implementation under 3.3.3 (page 72). you can grab a copy of the reference from my stash here - 
https://app.box.com/s/vz6lewz3eitovlvsshgr

**Comment by magicboker** [comment]
I traced the codes:
PDFDocumentCopyingContext::AppendPDFPageFromPDF -> PDFDocumentHandler::AppendPDFPageFromPDF -> PDFDocumentHandler::CreatePDFPageForPage -> PDFDocumentHandler::CopyPageContentToTargetPage(PDFPage* inPage,PDFDictionary* inPageObject) -> PDFDocumentHandler::WritePDFStreamInputToContentContext -> PDFDocumentHandler::WritePDFStreamInputToStream -> PDFParser::CreateInputStreamReader return NULL
Could you please give me some advise to modify your SDK for copying pages without the implementation of unsupported decode filters?

**Comment by galkahana** [comment]
PDFDocumentHandler::WriteStreamObject implements direction copying.  Im guessing that whnlen copying page content stream as is it can be used instead of the current method. At least if the first one fails

**Comment by magicboker** [comment]
Based on your suggestion,
How about i modify the codes in PDFDocumentHandler::CopyPageContentToTargetPage ?
```
EStatusCode PDFDocumentHandler::CopyPageContentToTargetPage(PDFPage* inPage,PDFDictionary* inPageObject)
{
    ...
	...
	status = WritePDFStreamInputToContentContext(pageContentContext,contentStream.GetPtr());
// insert blindly steam copying code - begin
	if (status != PDFHummus::eSuccess) // try blindly stream copying
		status = WriteStreamObject(contentStream.GetPtr());
// insert blindly steam copying code - end
	...
	...
}
```

**Comment by galkahana** [comment]
Hi, just checked in code that should do passthrough copying of the page content streams. you can pull it and try it out. let me know if it works.

the missing part is that once you copy a stream (can be done with a plain CopyObject) than you need to add a reference to the page for this content stream.
look here for the specific code:
https://github.com/galkahana/PDF-Writer/commit/0c16f249aeee4ad23a7ade63a72e66230d53b115#diff-86a7804e14e45578f1114a4091923fd2R1031

if this works for you, then we got a solution. if you could please send me the failing pdf than in the future if i'll do lzw decoding i can use it as a test file.

Gal.

**Comment by magicboker** [comment]
The attached PDF is what you want for verifying your solution of copy pages of one PDF to the other that use LZWDecode filter in the stream objects.



BR,
Tim Chen
magicboker@gmail.com

**Comment by magicboker** [comment]
Your solution works!!
I will test more PDFs and let you know if any problem or side effect occurs.

**Comment by galkahana** [comment]
Good. thanks.
