### ISSUE TITLE
FontDescriptorWriter::WriteFontDescriptor() does not write the required entry for the "Type" key in the Font Descriptor dictionary

### ISSUE THREAD

**Issue by TheGS** [galkahana/PDF-Writer#46]
The PDF specification requires that a Font Descriptor dictionary have a "Type" entry with a name value that is "FontDescriptor". The code in FontDescriptorWriter.cpp, in FontDescriptorWriter::WriteFontDescriptor() omits this required key and name value, and Adobe Acrobat's preflight checker flags this as an issue in the output.

**Comment by galkahana** [comment]
Thanks.
Corrected in [recent commit](https://github.com/galkahana/PDF-Writer/commit/0d94ddb2fd5ff7ed18716169f63f5d4b82997d9d).
