### ISSUE TITLE
Add new object to PDF file.

### ISSUE THREAD

**Issue by varMari** [galkahana/PDF-Writer#48]
Hello, 
Can i add new PDFDictionary object in my PDF document with your library?

**Comment by galkahana** [comment]
yes.

This entry discusses dictionary creation:
https://github.com/galkahana/PDF-Writer/wiki/The-ObjectsContext-Object#dictionary-writing

This is more in general about using low level commands:
https://github.com/galkahana/PDF-Writer/wiki/Extensibility

examples for writing dictionaries in a modified document envrionment:
https://github.com/galkahana/PDF-Writer/blob/master/PDFWriterTestPlayground/ModifyingExistingFileContent.cpp
