### ISSUE TITLE
Extracting Text from PDF

### ISSUE THREAD

**Issue by hashdefine1** [galkahana/PDF-Writer#56]
First of all many thanks for writing such a fantastic pdf library in C++. 
I saw an old discussion about this for JS but I am not sure if there is any C++ API to just extract basic text from a PDF, something like apache pdfbox textstripper.
I know this is naive but having a straight forward API would help for many scenarios where we just want to read specific elements.

**Comment by galkahana** [comment]
I'm afraid that there's no such API. Building such a capability on top of the existing PDFHummus library parsing abilities is possible, though. 
but then, if there's apache pdfbox textstripper why not use that?

**Comment by hashdefine1** [comment]
Actually my app is in C++. Calling Java from C++ works for me but overall it becomes slower compared to calling native C++ code.

**Comment by galkahana** [comment]
I meant the c++ lib. The nodejs module is just a shell around it.

**Comment by hashdefine1** [comment]
pdfbox is only Java, so won't work. 
I understand that PDFHummus library is rich enough and we can write a function on top to write the text stripper. I just wanted to check if such a function already exists. 
In case I succeed in writing it, I'll post it in one of the forums.

**Comment by galkahana** [comment]
extracting text with hummus http://pdfhummus.com/post/156548561656/extracting-text-from-pdf-files

**Comment by VanushVaswani** [comment]
@galkahana  does this handle compression?

> extracting text with hummus http://pdfhummus.com/post/156548561656/extracting-text-from-pdf-files

**Comment by galkahana** [comment]
Now also in c++:
https://github.com/galkahana/pdf-text-extraction
