### ISSUE TITLE
PDFModifiedPage class issue

### ISSUE THREAD

**Issue by Lidia321** [galkahana/PDF-Writer#58]
Hi Gal,

What's up ? 

I have to add some content to existing pdf page.

Should 
PDFModifiedPage class ( from 
https://github.com/galkahana/PDF-Writer/blob/master/PDFWriterTestPlayground/PageModifierTest.cpp) do the work ( add something to current content ) ? 

If not ( means, it is supposed to replace the page's current content with new one added between StartContentContext and EndContentContext like it does now), how can to keep current content ?

Thanks and cheers.
Lidia.

**Comment by galkahana** [comment]
Hi Lidia,
The PageModifier adds new content on top of the existing page content.
When using it then you should be aware that I recently added another flag to its constructor which you should probably use. like this:

    PDFModifiedPage modifiedPage(&pdfWriter,0,true);

It encapsulates the existing content with save..restore, so what content you add is not affected by non encapsulated settings of the existing content, such as a transformation matrix.

Regards,
Gal.

**Comment by Lidia321** [comment]
Hi again, Gal.

This is what I thought too :).

Unfortunatelly, it does not work. My guess this is probably some bug with specific pdf that is attached.
[AMERICAN FOOTBALL.PDF](https://github.com/galkahana/PDF-Writer/files/404276/AMERICAN.FOOTBALL.PDF)

Code is taken from example you've provided in 
https://github.com/galkahana/PDF-Writer/blob/master/PDFWriterTestPlayground/PageModifierTest.cpp

Could you advice, please ?

Thanks and cheers.
Lidia.

void main()
{

	EStatusCode status = eSuccess;
	PDFWriter pdfWriter;

	do
	{

		
		// open file for modification
		status = pdfWriter.ModifyPDF(
			"AMERICAN FOOTBALL.PDF",
			ePDFVersion13,
			"outout.pdf");
		

		PDFModifiedPage modifiedPage(&pdfWriter, 0, true);

		AbstractContentContext* contentContext = modifiedPage.StartContentContext();
		
		AbstractContentContext::TextOptions opt(
			pdfWriter.GetFontForFile("PDFHummus\\TestMaterials\\fonts\\arial.ttf"),
																			14,
																			AbstractContentContext::eGray,
																								   0
			);

		contentContext->WriteText(75,805,"Test Text",opt);

		modifiedPage.EndContentContext();
		modifiedPage.WritePage();
		
		status = pdfWriter.EndPDF();
		
	} while (false);
}

**Comment by galkahana** [comment]
Yap.
Had a problem there with one method to write contents to a page.

fixed it now in [latest commit](https://github.com/galkahana/PDF-Writer/commit/5a017d340ef7183bb510956e6b31d87959098f90).

**Comment by Lidia321** [comment]
It works - thanks a lot for quick fix.

Cheers.
Lidia.
