### ISSUE TITLE
[Question] How to correctly skip a failed object copying?

### ISSUE THREAD

**Issue by magicboker** [galkahana/PDF-Writer#59]
I need to copy objects from one PDF to the other PDF, but sometimes some objects are not "valid" (problematic PDF file maybe generated by some buggy PDF apps), i.e. missing parent node, or missing any indirect object. In such cases, i want to skip the object copying, but when PDFDocumentCopyingContext::CopyObject return eFailure, it already allocated some object ID such that in the later pdfWriter.EndPDF() always returned eFailure due to unwritten objects in the xRefTable (failed in ObjectsContext::WriteXrefTable line: 204).
Is there any method in the library that i can call to roll-back the states before the failed CopyObject call?

**Comment by galkahana** [comment]
Probably not cause by that time some content is already written to the file and its a bit contrary to how pdfwrite doesnt things to go back.
How about you tell me more about why copying failes? Do you have a sample?

(Alternatively you could always work with two pdfs. Do action first on one, if doesnt fail, do on the other one)

**Comment by magicboker** [comment]
Please check this sample [PDF](https://dl.dropboxusercontent.com/u/21305787/missing_obj_sample.pdf)

**Comment by galkahana** [comment]
Well, this is something that PDFWriter should be corrected to handle. i mean, it is a valid possibility.

Gal.

**Comment by magicboker** [comment]
The ideal result is to skip the object copy on missing objects only.
i.e. for the missing object ID = 16, referenced by the other object (ID = 19) in its "Parent" entry, just skip copying the object whose ID = 16 and keep the destination exactly the same with the source is ideal although the missing condition will still preserve in the destination.

**Comment by galkahana** [comment]
I could make it into copying a null in this case, or create a deleted object entry. We will have to see which would be a more reliable recreation  of the origin

**Comment by magicboker** [comment]
Do you mean to copy assign a deleted object ID (marked as unused in the xRefTable) for a missing object?

**Comment by galkahana** [comment]
that's a good option - if that's what makes 16 missing. is 16 marked as such? is it simply null? whatever it is in the source document...it's probably best to do the same in the target. i'm taking a look now

**Comment by magicboker** [comment]
A missing object could be marked as deleted or not exist in the xRefTable. I guessed the solution you purposed is to add a deleted entry in the xRefTable if it does not exist in the xRefTable.

**Comment by galkahana** [comment]
yap. committed a solution along this line [now](https://github.com/galkahana/PDF-Writer/commit/7ae08cb8b8f7ecd7ea66e2d2d0e369b2627e3b97). you can try it out. for me it worked well on the sample file, copying the annotation, and i also tried to append a page and it seemed to create a PDF is fine.

**Comment by magicboker** [comment]
Thank you very much for the solution!

However, do you have a solution for the case that a missing object has no associated deleted entry in the xRefTable?

**Comment by galkahana** [comment]
Look, it's valid to have deleted elements. the lib should take care of this case. it didn't and thanks to your note it's ok now.
anything else is just invalid. there are plenty possible exceptions. we could have an element pointing to an element it shouldn't (just having a wrong xref). xref table could be providing wrong positions (someone sent me a PDF like that recently). i think failing is a good policy then. 

we could be writing another version of the copying method to handle all possible cases and fill up things with deleted elements (for instance, it could just do what i did for all "else" cases), but i feel that sometimes its ok to just fail if the file is invalid.

If you have an actual PDF that bothers you and you think we can figure out a good way out, we can tailor something around it together.

Gal.

**Comment by magicboker** [comment]
You are right!
