### ISSUE TITLE
[Question] How to check and add a font into DR dictionary of the interactive form dictionary (AcroForm) in the catalog dictionary?

### ISSUE THREAD

**Issue by magicboker** [galkahana/PDF-Writer#62]
I need to create an interactive form (AcroForm) if it does not exist in a PDF.
Then, check and add a Font entry in the DR dictionary of the AcroForm dictionary.
How to achieve that in this library?
![AcroForm specs](https://dl.dropboxusercontent.com/u/21305787/acroform_table_dr.png)

**Comment by galkahana** [comment]
Creating the Acroform object can be done using the extensibility method of the Object Context. you can read about them here - https://github.com/galkahana/PDF-Writer/wiki/The-ObjectsContext-Object

specifically you will be looking into creating a new indirect object and a dictionary inside it.
There's a sample here - http://pdfhummus.com/post/45501642143/how-to-extend-the-library-adding-comments-to - on creating new types of objects (it creates annotations there, but the principal is the same).

You will also need to add a reference to the acroform from the catalog object.
you do that by implementing a handler for`OnCatalogWrite` method of `IDocumentContextExtender ` and attaching a listener prior to the pdfwriter ending.

you can read about it here:
https://github.com/galkahana/PDF-Writer/wiki/The-DocumentContext-Object#extending-document-context-level

As for the resource dictionary. A, seems like it is optional, and i think that it should remain so. this will cause acrobat or whomever to make decisions on how to implement the interactive parts in terms of fonts and such.
If you do want to create a resource dictionary and use a custom font, then you can use the [ResourcesDictionary](https://github.com/galkahana/PDF-Writer/blob/master/PDFWriter/ResourcesDictionary.h) class.
to learn how to write its entry in DR, follow how Page writing does it - 
https://github.com/galkahana/PDF-Writer/blob/master/PDFWriter/DocumentContext.cpp#L686

The last bit is the font, and it's a good question how to embed it. it's a bit tricky, but i'm guessing that it goes through reusing PDFWriter capabilties.  You can create a PDFUsedFont for your font (in a similar manner to how you normally do it), and then add all letter through EncodeStringForShowing, like done here:
https://github.com/galkahana/PDF-Writer/blob/master/PDFWriter/AbstractContentContext.cpp#L1102

but honestly i don't think that you need this part. so skip it first and only if things dont work do it (i mean...at least see some sample PDFs with forms and see if they have it and what is written there)

Regards,
Gal.

**Comment by magicboker** [comment]
When i use a standard done, like Helvetica, do i still need to embed it ? and do I need to find the system font file path for loading it?

**Comment by galkahana** [comment]
no need to embed at all, no need to declare. the system will take care of itself.
helvetica is one of the 14 basic fonts that are expected to be available. you can embed (and with hummus, unless you use Tj operator directly, this will be the case), but you don't have to.

**Comment by magicboker** [comment]
How to load it to construct a PDFUsedFont instance for Tf ?
i.e. contentContext->Tf(font,14) need the font object?

**Comment by galkahana** [comment]
Good question.
When using non embedded font you can use TfLow and TjLow to provide string values directly:
https://github.com/galkahana/PDF-Writer/wiki/Text-support#low-level-text-commands


Regards,
Gal.

**Comment by magicboker** [comment]
contentContext->TfLow("Helvetica",14);
contentContext->TjLow("Hello world!");

am i doing right?

**Comment by galkahana** [comment]
Amazing :)

**Comment by magicboker** [comment]
To write an non-ascii unicode, the TjLow seemed need some other works to handle the text encoding stuffs. If i simply convert my UTF8 strings to UTF16BE unicode string, adobe reader doesn't know the encoding. Can i use Tj to get rid of the encoding troubles?

**Comment by galkahana** [comment]
if you want to write non ascii unicode than you must embed a font in the regular way of using Tj with PDFUsedFont.
it will take care both of the necessary encoding and embedding (the encoding is pretty much a derivative of the embedding).

now would be a good time to ask - in what context are you planning to write? it seems to be that we are outside of the form question, right?

**Comment by magicboker** [comment]
Yes, i found a way to avoid to creating interactive form but to create an appearance stream (formXObject) for my "FreeText" annotation. Without an appearance stream or a font entry in the interactive form, Adobe reader will not show my created free text annotation.

**Comment by galkahana** [comment]
it's ok. sound like you did just the right thing.

**Comment by magicboker** [comment]
A question about font:
If my Tj input texts include some CID chars, do i need to set a CID included font such that all CID chars will be rendered correctly?

**Comment by galkahana** [comment]
If you are using pdfused font versions then hummus will create the required cid representation. I worked quite hard on this :). You just pass utf8 encoded unicodes and make sure the font that you are using has these chars

**Comment by magicboker** [comment]
For example, if the text includes some Chinese chars, and i set font Helvetica (that might not have chinese glyphs) by loading the font file, Helvetica.dfont, will anything go wrong?

**Comment by TheGS** [comment]
Helvetica.dfont likely contains a TrueType font. FreeType can use the .dfont file directly, but we found that we had to extract the sfnt for the font we wanted from the .dfont and shove it into a standalone .ttf file.  We also happen to do our own font fallback, so we look for cases where the 0 glyph is used for any character, and we ourselves look for a font that will display that character.

**Comment by magicboker** [comment]
Will you generate multi-textlines drawing commands based on the text input and a bounding box? or it's one textline drawing per Tj command?

**Comment by galkahana** [comment]
Tj (it writetext) will write a staright line. I have some measuring method somewhere so you should be able to implements wrapping yourself

בתאריך 18 באוג׳ 2016 8:10 אחה״צ,‏ magicboker <notifications@github.com> כתב:

Will you generate multi-textlines drawing commands based on the text input and a bounding box? or it's one textline drawing per Tj command?

**Comment by galkahana** [comment]
Here https://github.com/galkahana/PDF-Writer/wiki/Text-support#measuring-text

**Comment by magicboker** [comment]
Thank you very much for the detail instructions!!

**Comment by magicboker** [comment]
I tested it by writing a simple chinese char, unicode = 0x5927 (大), into the appear stream (formXObject), but it ended up with 0 Tj
```
NSString *fontFilePath = [[NSBundle mainBundle] pathForResource: @"SFNSDisplay-Regular" ofType: @"off"];
PDFUsedFont *font = documentContext.GetFontForFile([fontFilePath UTF8String], 0);
PDFFormXObject *xobjectForm = documentContext.StartFormXObject(bbox, matrix);
formXObjectID = xobjectForm->GetObjectID();
XObjectContentContext *xobjectContentContext = xobjectForm->GetContentContext();
xobjectContentContext->q();
xobjectContentContext->BT();
xobjectContentContext->rg(r, g, b);
xobjectContentContext->Tf(font, fontSize);
xobjectContentContext->Td(x, y);
xobjectContentContext->Tj([contents UTF8String]);
xobjectContentContext->ET();
xobjectContentContext->Q();
documentContext.EndFormXObjectAndRelease(xobjectForm);
```

**Comment by galkahana** [comment]
Right. It can match the unicode value to a glyphs id. It normally works, fonts have unicode mapping that free type reads. If you can find a method to figure out the glyphs id, then hummus can accept glyphids directly with an over Liad of tj

**Comment by magicboker** [comment]
I tried the other font, "PingFang.ttc".
It seemed converted to a wrong hex string "<30393566> Tj".
Instead, it should show "<5927> Tj".

**Comment by galkahana** [comment]
nope. it should be the glyph index. It is the glyph index as it is in the embedded font representation.
In most cases of True Type fonts (per the algorithm i chose, and i think this is what most do) this would be pretty much the original font glyph index.

Did it come out ok?

Gal.

**Comment by magicboker** [comment]
It didn't show up in acrobat and other pdf readers. That's why i went to check what  some pdf annotate apps generated for the single chinese char. They all show unicode encoded hex string in Tj.

**Comment by TheGS** [comment]
What we do when GetGlyphsForUnicodeText() fails is to scan through our original text and for any characters that cannot be represented by the desired font (e.g. it simply does not have any glyph to show for that Unicode character), we do our own font fallback to find an alternate font that does have a glyph for that Unicode character.  For example, when we have mixed Asian text in Helvetica, we will generally find that it will fail to obtain glyphs in the Helvetica font for some Chinese characters, and so we use other facilities in the operating system [e.g. CTFontCreateForString() on Mac, IMLangFontLink class on Windows, etc.] to identify an alternate font to show those characters.

**Comment by magicboker** [comment]
The font, "PingFang.ttc" did have the simple chinese char and generated the hex string with Tj operator. However, it didn't show up in pdf readers.

**Comment by TheGS** [comment]
On the Mac, that's /System/Library/Fonts/PingFang.ttc, I guess.  What is the Unicode codepoint of the character you're trying to display?  I think PDFWriter delegates much of this character-glyph mapping to FreeType if it can for TrueType and OpenType fonts, and it may be that you have to go a bit further to explicitly select a charmap at the FreeType level with FT_Select_Charmap().

**Comment by magicboker** [comment]
I put a chinese char unicode, 0x5927 (大). It means "big" in english.

**Comment by TheGS** [comment]
PingFang.ttc contains something like 18 fonts. Did you pick any specific one in that file?

**Comment by magicboker** [comment]
No, what else should i do to select a "sub-font" in the library?
I used the Tf and then Tj function calls
AbstractContentContext::Tf(PDFUsedFont* inFontReference,double inFontSize)
AbstractContentContext::Tj(const std::string& inText)

**Comment by galkahana** [comment]
`GetFontForFile` can have a 2nd parameter to select a font by its index, when using a font package. by default it picks the first one (0).

**Comment by galkahana** [comment]
i'm not getting success with PingFang for regular romans either (appears blank). this might mean a problem in embedding. the glyph index makes sense?

**Comment by galkahana** [comment]
ok. i tried some old versions of hummus. they were defo functioning better in terms of unicode work.
i'm gonna get to the bottom of this.

**Comment by galkahana** [comment]
@magicboker @TheGS 
seems like i had a really bad bug with the creation of fonts containing unicode charachters. something that i recently introduced that ruined hex representation of chars.

in any case, i fixed the issue now.

now its seems like i can get 0x5927 to appear correctly with the windows simsun.ttc font and with mac PingFang.ttc.

i say not too bad for a day of work :). that was a ghastly one.

**Comment by KarlHegbloom** [comment]
Good job. What about ligatures output by TeX or TeXmacs, not being spoken
by Android PDF readers? How to make it pronounce the ligature (fi, ff)
glyph as the glyphs it stands in for would be pronounced?

**Comment by TheGS** [comment]
Complex text shaping (which includes the many-to-one glyph substitution to ligature glyphs) is beyond the scope of FreeType by itself.

For us, we do extremely simple glyph substitution before handing the text and glyph lists off to Hummus (this along with other geometric transformations lets us do Asian vertical text), though we haven't attempted the many-to-one substitutions required for ligatures yet.

Adopting a cross-platform text shaping library like [HarfBuzz](https://en.wikipedia.org/wiki/HarfBuzz) would probably solve this problem, though it might require updating the FreeType bundled with Hummus, and the last time I checked (a while ago), there was something of a circular dependency between FreeType and HarfBuzz.

**Comment by KarlHegbloom** [comment]
Thank you for helping us new people learn more about how it all works.

**Comment by galkahana** [comment]
this looks promising:
https://github.com/tangrams/harfbuzz-icu-freetype

[icu would be nice for bidi]

**Comment by magicboker** [comment]
Great job!! galkahana!
