### ISSUE TITLE
Type1ToCFFEmbeddedFontWriter::AddComponentGlyphs() uses the private encoding for dependent glyphs even for glyphs defined using the 'seac' operator

### ISSUE THREAD

**Issue by TheGS** [galkahana/PDF-Writer#64]
The 'seac' operator ("Standard Encoding Accented Character") is defined to specify dependent glyphs in the Adobe Standard Encoding rather than the Type 1 font's private encoding, but the implementation of Type1ToCFFEmbeddedFontWriter::AddComponentGlyphs() was only getting the glyph names according to the font's private encoding.  In our case, we were getting glyph names defined in the font's private encoding dictionary, but the font did not actually have any charstrings for those glyph names. This caused the recursive call to AddComponentGlyphs() to fail on calling Type1Input::CalculateDependenciesForCharIndex(), and that led to the failure to embed the font, and ultimately the failure to complete the PDF.  Or, no glyph would be shown at all in the output PDF.
For example, the charstring for "Aring" might use 'seac' with "A" and "ring" as dependent glyphs, specified in the Adobe Standard Encoding (where "ring" has the code point 0xCA). The font's private encoding might have a different name for the code point 0xCA, "eth"... if the font did not have a charstring for "eth", that would lead to the failure described above; and if the font did have a charstring for that character, the wrong glyph would be drawn.
Our solution was to get the encoded glyph name explicitly from the StandardEncoding object instead.

**Comment by galkahana** [comment]
Good. How about you add your solution to hummus?

**Comment by TheGS** [comment]
I'd like to, especially since this particular modification itself is trivial to do, but I'm limited in how _directly_ I can contribute at this time. I'm working on changing that, though

**Comment by galkahana** [comment]
@TheGS just to clarify this. basically if something coming from seac then Type1Input::GetGlyphCharStringName() should be forced to go to the else part? i could add a "force" there in that case. would that make sense?

On another matter. mind looking if my latest commit is not complete idiocy - adding support for symbol encoding, hoping i don't hurt anything...seems like i don't, but i wanted an expert opinion. here - https://github.com/galkahana/PDF-Writer/commit/fa35726e4101f39621a86c82e77993195b36c509

**Comment by TheGS** [comment]
It looks like the only code that ever sets CharString1Dependencies::mCharCodes is Type1Input::Type1Seac() and the only code that ever consumes CharString1Dependencies::mCharCodes is Type1ToCFFEmbeddedFontWriter::AddComponentGlyphs(), so it should be safe to just get the encoded glyph name from StandardEncoding inside the AddComponentGlyphs() implementation.. in the case of 'seac', the encoding of the font never needs to be consulted, since 'seac' requires its component character glyph codes to be in Adobe Standard Encoding by definition.  That's what we ended up doing.

**Comment by galkahana** [comment]
Makes sense. Thanks

**Comment by galkahana** [comment]
k. should be taken care of with https://github.com/galkahana/PDF-Writer/commit/cc3b48f95168d2398658494f84378fe2ba9aeb33
