### ISSUE TITLE
Type1Input::ParseSubrs() makes assumptions about format of /Subrs dictionary entries that can lead to crashes with older Type 1 fonts

### ISSUE THREAD

**Issue by TheGS** [galkahana/PDF-Writer#76]
The code in **Type1Input::ParseSubrs()** assumes that each entry in the **/Subrs** dictionary uses the **NP** and **ND** shortcuts, and this can lead to a crash.

The assumption is that each entry will look like this in all Type 1 fonts:

> **dup** _index_ _numBytes_ **RD** _[numBytes of binary data]_ **NP**

However, **NP** (and **ND**) are procedures that are locally defined in the Type 1 font as abbreviations to save space in the font file...

> **/ND** { noaccess def } executeonly def
> **/NP** { noaccess put } executeonly def

Most fonts do use them, but some older fonts do not, using the full commands **noaccess**, **put**, and **def** in place.  For example, ...

So, instead of...

> **/Subrs** 115 array
> dup 0 15 RD _~15~bytes~_ NP
> dup 1 9 RD _~9~bytes~_ NP
>  :
>  :
> ND

an older font might have...

> **/Subrs** 115 array
> dup 0 15 RD _~15~bytes~_ noaccess put
> dup 1 9 RD _~9~bytes~_ noaccess put
>  :
>  :
> noaccess def

In the code for **Type1Input::ParseSubrs()**, after reading the binary bytes of the first entry, it does _exactly two_ further calls to `mPFMDecoder.GetNextToken()`, expecting to eat up the **NP** token then either the **dup** token or the **ND** token to be ready to read the key (subrIndex) of the next dictionary entry or be finished with the dictionary.

When presented with a font that does not use **NP** or **ND**, the next token after reading the first entry is now the **dup** in the second entry rather than the key (subrIndex) for that entry. Further entries in the `mSubrs` array are now garbage, and at some point, a 0 `CodeLength` may used to create an empty `Byte` array on the heap.

``` C++
mSubrs[subrIndex].CodeLength = Int(token.second);
mSubrs[subrIndex].Code = new Byte[mSubrs[subrIndex].CodeLength];
```

This can lead to a crash later in **Type1Input::FreeTables()**, when the `mSubrs` array is cleaned up.

``` C++
for(long i=0;i<mSubrsCount;++i)
    delete[] mSubrs[i].Code;
```

We don't have code for a general solution (since essentially, this is a problem of the fact that the Type 1 font is actually a Postscript program), but what we have come up with replaces the two of the calls to `mPFBDecoder.GetNextToken()` in **Type1Input::ParseSubrs()** :

So that...

``` C++
// skip NP token
mPFBDecoder.GetNextToken();

// skip dup or end array definition
mPFBDecoder.GetNextToken();
```

... is replaced with ...

``` C++
while ( token.first )
{
    token = mPFBDecoder.GetNextToken();
    if ( 0 == token.second.compare("dup") )
        break;
    if ( 0 == token.second.compare("ND") )
        break;
    if ( 0 == token.second.compare("def") )
        break;
}
```

That handles the cases where the font uses the **NP** and **ND** shortcuts, or if they use **noaccess**, **put**, and **def** directly.

Section 2.4 of the Type 1 specification also notes that some fonts can also use other names defined in **userdict**, or **-|**, **|-**, and **|** defined in the **Private** dictionary.

**Comment by TheGS** [comment]
I can't provide sample fonts to demonstrate this, since the two fonts originally identified as crashing were not provided to me, and I don't know the provenance of the one that was given to me (a 1987 version of Adobe Futura Condensed packaged as a Mac font suitcase).

**Comment by TheGS** [comment]
In our case, we also ran into a font (a 1999 version of ITC Avant Garde Gothic Book packaged as a Mac font suitcase) that used the **|-** shortcut for **ND** in the **Private** dictionary, so we had to adust our version of **Type1Input::ParseSubrs()** a bit...
```C++
	while ( token.first )
	{
		token = mPFBDecoder.GetNextToken();

		if ( 0 == token.second.compare("dup") )
			break;
		if ( 0 == token.second.compare("ND") )
			break;
		if ( 0 == token.second.compare("|-") ) // synonym for "ND"
			break;
		if ( 0 == token.second.compare("def") )
			break;
	}
```

Sorry for not providing anything straightforwardly mergable

**Comment by galkahana** [comment]
well, easy enough to follow, once i put my mind to it. 
committed here - https://github.com/galkahana/PDF-Writer/commit/7e03bb74702d1fbb0fa0cdc8a81e1fbb88ad610d

Gal.
