### ISSUE TITLE
[Question] How to get the UTF8 encoded string from a PDFLiteralString that has escaped characters?

### ISSUE THREAD

**Issue by magicboker** [galkahana/PDF-Writer#77]
I found a PDFLiteralString has a value of cstring: "3a\xb2bx + 15cxy + 25ady"
the "\xb2" in an escaped character with the octal value "0xb2".
How to convert the literal string to be a UTF8 encoded string?

**Comment by magicboker** [comment]
I already found a way to do so. therefore, i closed it.
the logic is simple:
If the text_len > 2, check if there is a BOM (FE FF) and use UTF16BE to encode it.
otherwise, check if all text are ascii (< 128), otherwise, encode the byte value to be a 2-byte sequence and replace the byte with the 2-byte sequence.

**Comment by galkahana** [comment]
Hi,
As an alternative you can use the libraries `PDFTextString`.

[short explanation](https://github.com/galkahana/PDF-Writer/wiki/PDF-Primitive-Objects)
[signature](https://github.com/galkahana/PDF-Writer/blob/master/PDFWriter/PDFTextString.h)
[usage example from another project of mine](https://github.com/galkahana/HummusJS/blob/master/src/PDFLiteralStringDriver.cpp#L103)
