### ISSUE TITLE
LC_NUMERIC may use decimal comma, thousand separator etc..

### ISSUE THREAD

**Issue by fajan** [galkahana/PDF-Writer#81]
locale settings affect sprintf, although pdf numbers should always use c locale.

I noticed it by MediaBox:
`/MediaBox [ 0 0 595,2 841,68 ]` (comma as decimal point, as in most European locale)

after writing this to a PDF, parsing it back fails.

fix could be in PrimitiveObjectsWriter.cpp:
<pre>#include &lt;sstream&gt;
#include &lt;locale&gt;
....
void PrimitiveObjectsWriter::WriteInteger(long long inIntegerToken,ETokenSeparator inSeparate)
{
	
	std::stringstream formatter;
	formatter.imbue(std::locale("C"));
	formatter << inIntegerToken;
	std::string formatter_buf = formatter.str();

	mStreamForWriting->Write((const IOBasicTypes::Byte *)formatter_buf.data(), formatter_buf.size());

	WriteTokenSeparator(inSeparate);
}
...

void PrimitiveObjectsWriter::WriteDouble(double inDoubleToken,ETokenSeparator inSeparate)
{
	std::stringstream formatter;
	formatter.imbue(std::locale("C"));
	formatter << inDoubleToken;
	std::string formatter_buf = formatter.str();

	mStreamForWriting->Write((const IOBasicTypes::Byte *)formatter_buf.data(),formatter_buf.size());
	WriteTokenSeparator(inSeparate);
}
</pre>

I'm tried this on aix/linux/msvc, and it fixed the issue.
Sorry, I can't create a pull request for it now.

**Comment by galkahana** [comment]
kinda took care of double writing in latest commit - https://github.com/galkahana/PDF-Writer/commit/4c85d4cd8500f4ddf49d4b7201cee328b29a955c
[guessing i can do integer too sometime...nothing too big]

thanks. if you could sometime make a pull request sometimes that would be nice.

**Comment by fajan** [comment]
okay, when I have some time I'll synch up the changes and do a pull request.
