### ISSUE TITLE
MergePDFPagesToPage the other way around?

### ISSUE THREAD

**Issue by hdijkema** [galkahana/PDF-Writer#82]
L.S.,

I see pdfPage is written out first and then test.pdf.
This results in a pdf file that hides my page with the content in the file (a word export).

MergePDFPagesToPage(pdfPage, "c:\\devel\\test.pdf", singePageRange); 

Could it also work the other way around?

**Comment by galkahana** [comment]
i'm afraid that you can't. in general content written later in time means it goes on top.
how about doing the merge prior to writing other content?

**Comment by hdijkema** [comment]
I solved the issue by using the 'page modifier'.

**Comment by seagrady2** [comment]
I was not able to solve this using the page modifier. I have been trying to add/remove watermarks from existing sample pdfs in the playground and have had no luck with either. The problem I'm having with adding is that my watermark always shows up being behind the other content. As well, when modifying I will need to add an object ID for deleting the object (the watermark) which would require getting the CurrentResourceDirectory from the ModifiedPage, but it is always null.
