### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by hdijkema** [galkahana/PDF-Writer#83]
Hi there. Thank you for your great library.
I'm looking for a way to align text (left, right, middle, center, etc.).
How should this be done?

**Comment by galkahana** [comment]
You will need to measure the text dimensions and place it per the alignment option in relation to the box.
For text to be placed in a PDF you can use the [text measurement](https://github.com/galkahana/PDF-Writer/wiki/Text-support#measuring-text) methods that exist in hummus

**Comment by hdijkema** [comment]
Thanks. That worked like a charm.
