### ISSUE TITLE
UnicodeString::FromUTF16UShort() shifts the high surrogate by 5 bits when it should shift by 10

### ISSUE THREAD

**Issue by TheGS** [galkahana/PDF-Writer#84]
In formula to combine high and low surrogate pairs into a Unicode codepoint, the code in UnicodeString::FromUTF16UShort() shifts the high surrogate left by 5 bits, but it really should shift left by 10 bits.
Compare with how both UnicodeString::ToUTF16BE() and UnicodeString::ToUTF16LE() perform the opposite conversion correctly by shifting the high 10 bits (out of the 20 bits obtained by subtracting 0x10000) as part of calculating the high surrogate.

**Comment by galkahana** [comment]
Thanks!
corrected in https://github.com/galkahana/PDF-Writer/commit/588af4565961eb09b820fe8bdb681d904fc6e2a7

**Comment by TheGS** [comment]
That commit fixed UnicodeString::FromUTF16UShort() and UnicodeString::FromUTF16LE(), but does the same change need to be made in UnicodeString::FromUTF16BE()?

**Comment by TheGS** [comment]
Oops, sorry.  I was looking at an out-of-date version, and I didn't see that UnicodeString::FromUTF16BE() had already been fixed in https://github.com/galkahana/PDF-Writer/commit/4a7b81f922b3f553555cbac3efcc58a80149d440
