### ISSUE TITLE
Could not modify pdf file

### ISSUE THREAD

**Issue by antonmok** [galkahana/PDF-Writer#89]
Hi Gal,
I am trying to draw some shapes and text in pdf but some files is not affected whatever 
operations I perform on  `PageContentContext*` .
I pass the problematic files to `TestBasicFileModification()` function from BasicModification test
and all operations returns `eSuccess`. Output pdf is created but page with "about" text is not inserted.
Also log file is not created.
Could you check what is wrong with attached pdf?
[test.pdf](https://github.com/galkahana/PDF-Writer/files/922366/test.pdf)

**Comment by antonmok** [comment]
I found that the new page is actually inserted but it is invisible for default Document Viewer in Ubuntu.
Adobe Acrobat shows new page as expected.

**Comment by antonmok** [comment]
Also when checking the list of fonts embedded in pdf Document Viewer do not list 
the Courier New font. But it should be here from couri.ttf file.
After rebuilding pdf using this tool https://www.pdf-online.com/osa/repair.aspx
the file is displayed correctly in Document Viewer.

**Comment by antonmok** [comment]
After running pdfinfo tool on modified pdf it says:

`Syntax Error: Couldn't find trailer dictionary`

**Comment by antonmok** [comment]
As I understand your library does not update some headers/tables in the beginning of pdf file after modification. And this is the reason why default Ubuntu viewer can not properly recognize file.
I temporary fix this issue by repairing the modified file with ghost script.
Is there any way to update document structure descriptors with your library?

**Comment by galkahana** [comment]
how about you send the original PDF, i might find time to look into running the sample with this file, and figuring this out.

and yes, you can update document structure descriptors with this library. in fact, most of the library is built in layers. if you wanna know how to do this, just look into the code that modifies the file.

Gal.

**Comment by antonmok** [comment]
Thanks for reply.
The attached file is original unmodified pdf which I use for tests.
[test.pdf](https://github.com/galkahana/PDF-Writer/files/933305/test.pdf)

**Comment by galkahana** [comment]
[test#89.pdf](https://github.com/galkahana/PDF-Writer/files/948920/test.89.pdf)

this is what i got running through TestBasicFileModification. i don't see anything wrong with it.
extra page. courier is embedded.
