### ISSUE TITLE
CreateImageXObjectFromJPGStream is not a function

### ISSUE THREAD

**Issue by marianopaulin02** [galkahana/PDF-Writer#90]
Hi! I'm new with Hummus, I'm trying to create an ImageXObject from a JPG Base64 buffer stream like it's explained here in the docs [Custom-input-and-output](https://github.com/galkahana/PDF-Writer/wiki/Custom-input-and-output#tiff-and-jpg-images-input),
but  when I run the code i got this error: "**pdfWriter.CreateImageXObjectFromJPGStream is not a function**"
 Here is my code
```
var pdfWriter = hummus.createWriter(__dirname + '/path/to.pdf',{version:hummus.ePDFVersion14});
var img = new Buffer( "data:image/jpeg;base64,  ...   ",'base64')
var imageXObject = pdfWriter.CreateImageXObjectFromJPGStream(img); //here the error
```
Thanks for your help in advance

**Comment by galkahana** [comment]
you might want to take a look in hummusjs documentation instead of pdfwriter.
see here - https://github.com/galkahana/HummusJS/wiki/Show-images#streams
