### ISSUE TITLE
How to compile as a dynamic link library

### ISSUE THREAD

**Issue by nihao2015** [galkahana/PDF-Writer#92]
Hi, 
I know how to compile PDF-Writer as a linux static library(*.a)， now I want to compile it as a dynamic link library on linux(*.so) and how to do it?
thanks!

**Comment by galkahana** [comment]
check out cmake documentation.
also note that note below:
https://github.com/galkahana/PDF-Writer/wiki/Building-and-running-samples#special-options-with-cmake

**Comment by gnat42** [comment]
I couldn't figure it out either so modified the PDFWriter/CMakeLists.txt
```
diff --git a/PDFWriter/CMakeLists.txt b/PDFWriter/CMakeLists.txt
index 137f841..5f64371 100644
--- a/PDFWriter/CMakeLists.txt
+++ b/PDFWriter/CMakeLists.txt
@@ -34,7 +34,7 @@ endif(NOT PDFHUMMUS_NO_PNG)
 
 
 
-add_library (PDFWriter 
+add_library (PDFWriter SHARED
 #sources
 AbstractContentContext.cpp
 AbstractWrittenFont.cpp
```

Wasn't sure of any other way to do it...

**Comment by samkots** [comment]
I tried the same. I was able to create a DLL, but it doesn't create a .lib file as nothing is getting exported from the DLL.
I found that none of the functions are marked with export macros.
So how the functions will be exported from the DLL?

**Comment by galkahana** [comment]
i think this should help you get there:
https://stackoverflow.com/questions/225432/export-all-symbols-when-creating-a-dll

short one - yes, no dll exports in code...so you will need to use .def files.
and it might be that you can modify the cmake setup to help you with this.

**Comment by samkots** [comment]
Thanks for your quick response..
Yes, actually I was thinking of writing a `.def` file..
Yes I have modified cmake setup and have generated a DLL. Just that it doesn't export anything.
Thanks for the link. It will be helpful.
Have you compiled it as a DLL that way?

Also I was wondering why there are no export macros. I know its a lot or work, but is there any plan?
If not, I am thinking of doing it in my free time. Will that be acceptable as a pull request?

**Comment by samkots** [comment]
Thanks to the link in your previous message, I was led [here](https://blog.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/).
I was able to create a DLL on Windows with this command:
`cmake -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE`
and on Linux with this command:
`cmake -DBUILD_SHARED_LIBS=TRUE`
without having to make a single change to any of the CMake file.
It also passed all the test cases.

**Comment by samkots** [comment]
Regarding export macros, yes that's a big effort.
My concern was just about the unnecessary symbols getting exported(if any).
Even on Linux, I use the `-fvisibility=hidden` which, just like Windows, hides all the symbols by default and then I put macros only on the functions that I want to export. This gives us control over what we are exporting.
Anyways, that's just my opinion..
Thanks :)
