### ISSUE TITLE
Support WebAssembly

### ISSUE THREAD

**Issue by viezel** [galkahana/PDF-Writer#94]
Would it be possible to support WebAssembly? 
if so, it would be possible to write a javascript based viewer with the power of C.

**Comment by galkahana** [comment]
i would definitely encourage anyone who wants to use this code and port (or whatever else is necessary) to webassembly. as for nice browser based pdf viewer, you can use pdfjs, it's quite powerful. pdf-writer, while allowing one to write a renderer for PDF, is not about that - rather, it's about the creation, parsing (for any usage) and modification of PDFs.

**Comment by galkahana** [comment]
k. that's actually quite a good idea. for once it would make it spr easy to work with react-native, which is of very special interest of mine.
i'm gonna see how hard it is to do this as well as adapt some i/o functionality for the web/react-native/nodejs-not-using-hummusjs environments.

**Comment by viezel** [comment]
sweet. I really think WebAssembly has some quick possibilities for many kinds of platforms

**Comment by Subtletree** [comment]
A web assembly port would be a game changer for me! I'm probably unable to help with implementation but keen to help with testing if needed.

**Comment by mlecoq** [comment]
Hi, any news about the support of web assembly ?
