### ISSUE TITLE
Compress and Linearize

### ISSUE THREAD

**Issue by viezel** [galkahana/PDF-Writer#98]
I cannot find any docs/example on how to compress a PDF. Secondly, I also need to linearize the output or as Adobe calls it "Optimize for Fast Web Preview".

Do you have any examples of how to achieve this?

sidenote: 
atm, im using Ghostscript for this, but its buggy and would love to move to this lib as its much faster! 

`gs -sDEVICE=pdfwrite -dUseCropBox -dPDFSETTINGS=/screen -dCompatibilityLevel=1.6 -dNOPAUSE -dBATCH -dDetectDuplicateImages=true -sOutputFile=processed.pdf  original.pdf`

**Comment by galkahana** [comment]
Hi, i don't do linearization. this is some decision i got when i started the project. linearization goes against a very fundamental idea in hummus, and it is that it flushes what it is being asked to draw directly to IO. this allows it to have a fairly constant low memory usage, as opposed to other solutions, and why it's possible to use it in io scenarios that can only move forward. linearization can only be done, then, as a post process, which i never got to, and its not on my list at this point. [something completely different is on my list right now, and it is an attempt to support web assembly].

As for compression, all pdfs coming out of hummus are compressed in the same manner. content stream as flates (zip), and images come out pretty much as is. i don't have anything more sophisticated.

**Comment by viezel** [comment]
Thanks for the answer. 
`linearization` makes sense. Good point.
`compress` I hope you will consider it, or maybe blog about how to compress content in order manners.
