### ISSUE TITLE
Support CID fonts

### ISSUE THREAD

**Issue by viezel** [galkahana/PDF-Writer#99]
Any plans on supporting CID fonts? I cannot decode the fonts atm. 

I know the PDFium lib has support for it for implementation inspiration:
https://github.com/documentcloud/pdfium/tree/master/third_party/freetype/src/cid

**Comment by galkahana** [comment]
CID fonts are not supported, you can use ttf and otf, for the larger fonts.

**Comment by viezel** [comment]
The issue at hand is that I use your lib for a microservice that modifies PDF fils on the fly. So I cannot decide which kind of PDFs i get. 
Are there any plans on support CID?

**Comment by galkahana** [comment]
Hmm. Not sure that i understand. You get a pdf which has cid font in it?

**Comment by viezel** [comment]
Yeah I think so. At least I cannot extract the text from it.

**Comment by galkahana** [comment]
ok. so you mean that the text parsing sample that i provided doesn't support cid.
well, that's not in the scope of this project. this project supports parsing files with CID fonts embedding them and what not.

**Comment by viezel** [comment]
This PDF: [publication_1284_original.pdf](https://github.com/galkahana/PDF-Writer/files/1224717/publication_1284_original.pdf)

I cannot decode the text:
`\u00003\u0000D\u0000J\u0000H\u0000V\u0000\u0003\u0000\u0017\u0000\u0013\u0000\u0003\u0000_\u0000\u0003\u0000\u0017\u0000\u0014\n\n\u0000J\u0000U\u0000R\u0000K\u0000H\u0000\u0011\u0000F\u0000R\u0000P\n\u00003\u0000D\u0000J\u0000H\u0000V\u0000\u0003\u0000\u0017\u0000\u0013\u0000\u0003\u0000_\u0000\u0003\u0000\u0017\u0000\u0014`

**Comment by galkahana** [comment]
Ok.  Did yiu refer to the articlr i wrote about text parsing? It has a sample script as well as explanation on how to expend it to support what not supported. Again. Not part of the scope for this project

**Comment by viezel** [comment]
Yes, went through it. I understand that its not part of this project. Anywhere else I can contact you?

**Comment by galkahana** [comment]
Gal.kahana@hotmail.com is where all the fun happens. One detail i dont know is - are you looking for a c++ solution or nodejs one?
